// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceSdwanArchiveFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceSdwanArchiveFeatureTemplateConfig,
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("data.sdwan_archive_feature_template.test", "path_to_archive_file_directory", "ftp://file-path"),
					resource.TestCheckResourceAttr("data.sdwan_archive_feature_template.test", "archival_interval", "52560"),
					resource.TestCheckResourceAttr("data.sdwan_archive_feature_template.test", "ssh_key_file", "id_rsa"),
					resource.TestCheckResourceAttr("data.sdwan_archive_feature_template.test", "vpn_id", "1"),
				),
			},
		},
	})
}

const testAccDataSourceSdwanArchiveFeatureTemplateConfig = `

resource "sdwan_archive_feature_template" "test" {
  name = "TF_TEST_MIN"
  description = "Terraform integration test"
  device_types = ["vedge-C8000V"]
  path_to_archive_file_directory = "ftp://file-path"
  archival_interval = 52560
  ssh_key_file = "id_rsa"
  vpn_id = 1
}

data "sdwan_archive_feature_template" "test" {
  id = sdwan_archive_feature_template.test.id
}
`
