// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Multicast struct {
	Id                types.String `tfsdk:"id"`
	Version           types.Int64  `tfsdk:"version"`
	TemplateType      types.String `tfsdk:"template_type"`
	Name              types.String `tfsdk:"name"`
	Description       types.String `tfsdk:"description"`
	DeviceTypes       types.Set    `tfsdk:"device_types"`
	Local             types.Bool   `tfsdk:"local"`
	LocalVariable     types.String `tfsdk:"local_variable"`
	Threshold         types.Int64  `tfsdk:"threshold"`
	ThresholdVariable types.String `tfsdk:"threshold_variable"`
}

func (data Multicast) getModel() string {
	return "multicast"
}

func (data Multicast) toBody(ctx context.Context) string {
	body := ""

	var device_types []string
	data.DeviceTypes.ElementsAs(ctx, &device_types, false)
	body, _ = sjson.Set(body, "deviceType", device_types)
	body, _ = sjson.Set(body, "factoryDefault", false)
	body, _ = sjson.Set(body, "templateDescription", data.Description.ValueString())
	body, _ = sjson.Set(body, "templateMinVersion", "15.0.0")
	body, _ = sjson.Set(body, "templateName", data.Name.ValueString())
	body, _ = sjson.Set(body, "templateType", "multicast")
	body, _ = sjson.Set(body, "templateDefinition", map[string]interface{}{})

	path := "templateDefinition."

	if !data.LocalVariable.IsNull() {
		body, _ = sjson.Set(body, path+"multicast-replicator.local."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"multicast-replicator.local."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"multicast-replicator.local."+"vipVariableName", data.LocalVariable.ValueString())
	} else if data.Local.IsNull() {
		body, _ = sjson.Set(body, path+"multicast-replicator", map[string]interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"multicast-replicator.local."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"multicast-replicator.local."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"multicast-replicator.local."+"vipValue", strconv.FormatBool(data.Local.ValueBool()))
	}

	if !data.ThresholdVariable.IsNull() {
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipVariableName", data.ThresholdVariable.ValueString())
	} else if data.Threshold.IsNull() {
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"multicast-replicator.threshold."+"vipValue", data.Threshold.ValueInt64())
	}
	return body
}

func (data *Multicast) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("deviceType"); value.Exists() {
		data.DeviceTypes = helpers.GetStringSet(value.Array())
	} else {
		data.DeviceTypes = types.SetNull(types.StringType)
	}
	if value := res.Get("templateDescription"); value.Exists() && value.String() != "" {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("templateName"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("templateType"); value.Exists() {
		data.TemplateType = types.StringValue(value.String())
	} else {
		data.TemplateType = types.StringNull()
	}

	path := "templateDefinition."
	if value := res.Get(path + "multicast-replicator.local.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.Local = types.BoolNull()

			v := res.Get(path + "multicast-replicator.local.vipVariableName")
			data.LocalVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.Local = types.BoolNull()
			data.LocalVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "multicast-replicator.local.vipValue")
			data.Local = types.BoolValue(v.Bool())
			data.LocalVariable = types.StringNull()
		}
	} else {
		data.Local = types.BoolNull()
		data.LocalVariable = types.StringNull()
	}
	if value := res.Get(path + "multicast-replicator.threshold.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.Threshold = types.Int64Null()

			v := res.Get(path + "multicast-replicator.threshold.vipVariableName")
			data.ThresholdVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.Threshold = types.Int64Null()
			data.ThresholdVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "multicast-replicator.threshold.vipValue")
			data.Threshold = types.Int64Value(v.Int())
			data.ThresholdVariable = types.StringNull()
		}
	} else {
		data.Threshold = types.Int64Null()
		data.ThresholdVariable = types.StringNull()
	}
}

func (data *Multicast) hasChanges(ctx context.Context, state *Multicast) bool {
	hasChanges := false
	if !data.Local.Equal(state.Local) {
		hasChanges = true
	}
	if !data.Threshold.Equal(state.Threshold) {
		hasChanges = true
	}
	return hasChanges
}
