// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Banner struct {
	Id                  types.String `tfsdk:"id"`
	Version             types.Int64  `tfsdk:"version"`
	TemplateType        types.String `tfsdk:"template_type"`
	Name                types.String `tfsdk:"name"`
	Description         types.String `tfsdk:"description"`
	DeviceTypes         types.Set    `tfsdk:"device_types"`
	LoginBanner         types.String `tfsdk:"login_banner"`
	LoginBannerVariable types.String `tfsdk:"login_banner_variable"`
	MotdBanner          types.String `tfsdk:"motd_banner"`
	MotdBannerVariable  types.String `tfsdk:"motd_banner_variable"`
}

func (data Banner) getModel() string {
	return "banner"
}

func (data Banner) toBody(ctx context.Context) string {
	body := ""

	var device_types []string
	data.DeviceTypes.ElementsAs(ctx, &device_types, false)
	body, _ = sjson.Set(body, "deviceType", device_types)
	body, _ = sjson.Set(body, "factoryDefault", false)
	body, _ = sjson.Set(body, "templateDescription", data.Description.ValueString())
	body, _ = sjson.Set(body, "templateMinVersion", "15.0.0")
	body, _ = sjson.Set(body, "templateName", data.Name.ValueString())
	body, _ = sjson.Set(body, "templateType", "banner")
	body, _ = sjson.Set(body, "templateDefinition", map[string]interface{}{})

	path := "templateDefinition."

	if !data.LoginBannerVariable.IsNull() {
		body, _ = sjson.Set(body, path+"login."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"login."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"login."+"vipVariableName", data.LoginBannerVariable.ValueString())
	} else if data.LoginBanner.IsNull() {
		body, _ = sjson.Set(body, path+"login."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"login."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"login."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"login."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"login."+"vipValue", data.LoginBanner.ValueString())
	}

	if !data.MotdBannerVariable.IsNull() {
		body, _ = sjson.Set(body, path+"motd."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"motd."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"motd."+"vipVariableName", data.MotdBannerVariable.ValueString())
	} else if data.MotdBanner.IsNull() {
		body, _ = sjson.Set(body, path+"motd."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"motd."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"motd."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"motd."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"motd."+"vipValue", data.MotdBanner.ValueString())
	}
	return body
}

func (data *Banner) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("deviceType"); value.Exists() {
		data.DeviceTypes = helpers.GetStringSet(value.Array())
	} else {
		data.DeviceTypes = types.SetNull(types.StringType)
	}
	if value := res.Get("templateDescription"); value.Exists() && value.String() != "" {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("templateName"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("templateType"); value.Exists() {
		data.TemplateType = types.StringValue(value.String())
	} else {
		data.TemplateType = types.StringNull()
	}

	path := "templateDefinition."
	if value := res.Get(path + "login.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.LoginBanner = types.StringNull()

			v := res.Get(path + "login.vipVariableName")
			data.LoginBannerVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.LoginBanner = types.StringNull()
			data.LoginBannerVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "login.vipValue")
			data.LoginBanner = types.StringValue(v.String())
			data.LoginBannerVariable = types.StringNull()
		}
	} else {
		data.LoginBanner = types.StringNull()
		data.LoginBannerVariable = types.StringNull()
	}
	if value := res.Get(path + "motd.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.MotdBanner = types.StringNull()

			v := res.Get(path + "motd.vipVariableName")
			data.MotdBannerVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.MotdBanner = types.StringNull()
			data.MotdBannerVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "motd.vipValue")
			data.MotdBanner = types.StringValue(v.String())
			data.MotdBannerVariable = types.StringNull()
		}
	} else {
		data.MotdBanner = types.StringNull()
		data.MotdBannerVariable = types.StringNull()
	}
}

func (data *Banner) hasChanges(ctx context.Context, state *Banner) bool {
	hasChanges := false
	if !data.LoginBanner.Equal(state.LoginBanner) {
		hasChanges = true
	}
	if !data.MotdBanner.Equal(state.MotdBanner) {
		hasChanges = true
	}
	return hasChanges
}
