// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Ospf struct {
	Id                                 types.String             `tfsdk:"id"`
	Version                            types.Int64              `tfsdk:"version"`
	TemplateType                       types.String             `tfsdk:"template_type"`
	Name                               types.String             `tfsdk:"name"`
	Description                        types.String             `tfsdk:"description"`
	DeviceTypes                        types.Set                `tfsdk:"device_types"`
	RouterId                           types.String             `tfsdk:"router_id"`
	RouterIdVariable                   types.String             `tfsdk:"router_id_variable"`
	ReferenceBandwidth                 types.Int64              `tfsdk:"reference_bandwidth"`
	ReferenceBandwidthVariable         types.String             `tfsdk:"reference_bandwidth_variable"`
	Rfc1583Compatible                  types.Bool               `tfsdk:"rfc_1583_compatible"`
	Rfc1583CompatibleVariable          types.String             `tfsdk:"rfc_1583_compatible_variable"`
	OriginateDefaultRoute              types.Bool               `tfsdk:"originate_default_route"`
	Always                             types.Bool               `tfsdk:"always"`
	AlwaysVariable                     types.String             `tfsdk:"always_variable"`
	DefaultMetric                      types.Int64              `tfsdk:"default_metric"`
	DefaultMetricVariable              types.String             `tfsdk:"default_metric_variable"`
	MetricType                         types.String             `tfsdk:"metric_type"`
	MetricTypeVariable                 types.String             `tfsdk:"metric_type_variable"`
	DistanceForExternalRoutes          types.Int64              `tfsdk:"distance_for_external_routes"`
	DistanceForExternalRoutesVariable  types.String             `tfsdk:"distance_for_external_routes_variable"`
	DistanceForInterAreaRoutes         types.Int64              `tfsdk:"distance_for_inter_area_routes"`
	DistanceForInterAreaRoutesVariable types.String             `tfsdk:"distance_for_inter_area_routes_variable"`
	DistanceForIntraAreaRoutes         types.Int64              `tfsdk:"distance_for_intra_area_routes"`
	DistanceForIntraAreaRoutesVariable types.String             `tfsdk:"distance_for_intra_area_routes_variable"`
	SpfCalculationDelay                types.Int64              `tfsdk:"spf_calculation_delay"`
	SpfCalculationDelayVariable        types.String             `tfsdk:"spf_calculation_delay_variable"`
	InitialHoldTime                    types.Int64              `tfsdk:"initial_hold_time"`
	InitialHoldTimeVariable            types.String             `tfsdk:"initial_hold_time_variable"`
	MaxHoldTime                        types.Int64              `tfsdk:"max_hold_time"`
	MaxHoldTimeVariable                types.String             `tfsdk:"max_hold_time_variable"`
	RedistributeRoutes                 []OspfRedistributeRoutes `tfsdk:"redistribute_routes"`
	RouterLsa                          []OspfRouterLsa          `tfsdk:"router_lsa"`
	RoutePolicies                      []OspfRoutePolicies      `tfsdk:"route_policies"`
	OspfArea                           []OspfOspfArea           `tfsdk:"ospf_area"`
}

type OspfRedistributeRoutes struct {
	Optional            types.Bool   `tfsdk:"optional"`
	Protocol            types.String `tfsdk:"protocol"`
	ProtocolVariable    types.String `tfsdk:"protocol_variable"`
	RoutePolicy         types.String `tfsdk:"route_policy"`
	RoutePolicyVariable types.String `tfsdk:"route_policy_variable"`
}

type OspfRouterLsa struct {
	Optional                  types.Bool   `tfsdk:"optional"`
	Type                      types.String `tfsdk:"type"`
	AdvertizementTime         types.Int64  `tfsdk:"advertizement_time"`
	AdvertizementTimeVariable types.String `tfsdk:"advertizement_time_variable"`
}

type OspfRoutePolicies struct {
	Optional           types.Bool   `tfsdk:"optional"`
	Direction          types.String `tfsdk:"direction"`
	DirectionVariable  types.String `tfsdk:"direction_variable"`
	PolicyName         types.String `tfsdk:"policy_name"`
	PolicyNameVariable types.String `tfsdk:"policy_name_variable"`
}

type OspfOspfArea struct {
	Optional              types.Bool                    `tfsdk:"optional"`
	AreaNumber            types.Int64                   `tfsdk:"area_number"`
	AreaNumberVariable    types.String                  `tfsdk:"area_number_variable"`
	StubNoSummary         types.Bool                    `tfsdk:"stub_no_summary"`
	StubNoSummaryVariable types.String                  `tfsdk:"stub_no_summary_variable"`
	Translate             types.String                  `tfsdk:"translate"`
	TranslateVariable     types.String                  `tfsdk:"translate_variable"`
	NssaNoSummary         types.Bool                    `tfsdk:"nssa_no_summary"`
	NssaNoSummaryVariable types.String                  `tfsdk:"nssa_no_summary_variable"`
	OspfInterface         []OspfOspfAreaOspfInterface   `tfsdk:"ospf_interface"`
	SummarizeRoutes       []OspfOspfAreaSummarizeRoutes `tfsdk:"summarize_routes"`
}

type OspfOspfAreaOspfInterface struct {
	Optional                         types.Bool   `tfsdk:"optional"`
	InterfaceName                    types.String `tfsdk:"interface_name"`
	InterfaceNameVariable            types.String `tfsdk:"interface_name_variable"`
	HelloInterval                    types.Int64  `tfsdk:"hello_interval"`
	HelloIntervalVariable            types.String `tfsdk:"hello_interval_variable"`
	DeadInterval                     types.Int64  `tfsdk:"dead_interval"`
	DeadIntervalVariable             types.String `tfsdk:"dead_interval_variable"`
	RetransmitInterval               types.Int64  `tfsdk:"retransmit_interval"`
	RetransmitIntervalVariable       types.String `tfsdk:"retransmit_interval_variable"`
	InterfaceCost                    types.Int64  `tfsdk:"interface_cost"`
	InterfaceCostVariable            types.String `tfsdk:"interface_cost_variable"`
	DesignatedRouterPriority         types.Int64  `tfsdk:"designated_router_priority"`
	DesignatedRouterPriorityVariable types.String `tfsdk:"designated_router_priority_variable"`
	OspfNetworkType                  types.String `tfsdk:"ospf_network_type"`
	OspfNetworkTypeVariable          types.String `tfsdk:"ospf_network_type_variable"`
	PassiveInterface                 types.Bool   `tfsdk:"passive_interface"`
	PassiveInterfaceVariable         types.String `tfsdk:"passive_interface_variable"`
	AuthenticationType               types.String `tfsdk:"authentication_type"`
	AuthenticationTypeVariable       types.String `tfsdk:"authentication_type_variable"`
	AuthenticationKey                types.String `tfsdk:"authentication_key"`
	AuthenticationKeyVariable        types.String `tfsdk:"authentication_key_variable"`
	MessageDigestKeyId               types.Int64  `tfsdk:"message_digest_key_id"`
	MessageDigestKeyIdVariable       types.String `tfsdk:"message_digest_key_id_variable"`
	MessageDigestKey                 types.String `tfsdk:"message_digest_key"`
	MessageDigestKeyVariable         types.String `tfsdk:"message_digest_key_variable"`
}
type OspfOspfAreaSummarizeRoutes struct {
	Optional            types.Bool   `tfsdk:"optional"`
	Address             types.String `tfsdk:"address"`
	AddressVariable     types.String `tfsdk:"address_variable"`
	Cost                types.Int64  `tfsdk:"cost"`
	CostVariable        types.String `tfsdk:"cost_variable"`
	NoAdvertise         types.Bool   `tfsdk:"no_advertise"`
	NoAdvertiseVariable types.String `tfsdk:"no_advertise_variable"`
}

func (data Ospf) getModel() string {
	return "ospf"
}

func (data Ospf) toBody(ctx context.Context) string {
	body := ""

	var device_types []string
	data.DeviceTypes.ElementsAs(ctx, &device_types, false)
	body, _ = sjson.Set(body, "deviceType", device_types)
	body, _ = sjson.Set(body, "factoryDefault", false)
	body, _ = sjson.Set(body, "templateDescription", data.Description.ValueString())
	body, _ = sjson.Set(body, "templateMinVersion", "15.0.0")
	body, _ = sjson.Set(body, "templateName", data.Name.ValueString())
	body, _ = sjson.Set(body, "templateType", "ospf")
	body, _ = sjson.Set(body, "templateDefinition", map[string]interface{}{})

	path := "templateDefinition."

	if !data.RouterIdVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipVariableName", data.RouterIdVariable.ValueString())
	} else if data.RouterId.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.router-id."+"vipValue", data.RouterId.ValueString())
	}

	if !data.ReferenceBandwidthVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipVariableName", data.ReferenceBandwidthVariable.ValueString())
	} else if data.ReferenceBandwidth.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.auto-cost.reference-bandwidth."+"vipValue", data.ReferenceBandwidth.ValueInt64())
	}

	if !data.Rfc1583CompatibleVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipVariableName", data.Rfc1583CompatibleVariable.ValueString())
	} else if data.Rfc1583Compatible.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.compatible.rfc1583."+"vipValue", strconv.FormatBool(data.Rfc1583Compatible.ValueBool()))
	}
	if data.OriginateDefaultRoute.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate."+"vipObjectType", "node-only")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate."+"vipObjectType", "node-only")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate."+"vipValue", strconv.FormatBool(data.OriginateDefaultRoute.ValueBool()))
	}

	if !data.AlwaysVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipObjectType", "node-only")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipVariableName", data.AlwaysVariable.ValueString())
	} else if data.Always.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipObjectType", "node-only")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipObjectType", "node-only")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.always."+"vipValue", strconv.FormatBool(data.Always.ValueBool()))
	}

	if !data.DefaultMetricVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipVariableName", data.DefaultMetricVariable.ValueString())
	} else if data.DefaultMetric.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric."+"vipValue", data.DefaultMetric.ValueInt64())
	}

	if !data.MetricTypeVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipVariableName", data.MetricTypeVariable.ValueString())
	} else if data.MetricType.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.default-information.originate.metric-type."+"vipValue", data.MetricType.ValueString())
	}

	if !data.DistanceForExternalRoutesVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipVariableName", data.DistanceForExternalRoutesVariable.ValueString())
	} else if data.DistanceForExternalRoutes.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.distance.external."+"vipValue", data.DistanceForExternalRoutes.ValueInt64())
	}

	if !data.DistanceForInterAreaRoutesVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipVariableName", data.DistanceForInterAreaRoutesVariable.ValueString())
	} else if data.DistanceForInterAreaRoutes.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.distance.inter-area."+"vipValue", data.DistanceForInterAreaRoutes.ValueInt64())
	}

	if !data.DistanceForIntraAreaRoutesVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipVariableName", data.DistanceForIntraAreaRoutesVariable.ValueString())
	} else if data.DistanceForIntraAreaRoutes.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.distance.intra-area."+"vipValue", data.DistanceForIntraAreaRoutes.ValueInt64())
	}

	if !data.SpfCalculationDelayVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipVariableName", data.SpfCalculationDelayVariable.ValueString())
	} else if data.SpfCalculationDelay.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.delay."+"vipValue", data.SpfCalculationDelay.ValueInt64())
	}

	if !data.InitialHoldTimeVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipVariableName", data.InitialHoldTimeVariable.ValueString())
	} else if data.InitialHoldTime.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.initial-hold."+"vipValue", data.InitialHoldTime.ValueInt64())
	}

	if !data.MaxHoldTimeVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipVariableName", data.MaxHoldTimeVariable.ValueString())
	} else if data.MaxHoldTime.IsNull() {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.timers.spf.max-hold."+"vipValue", data.MaxHoldTime.ValueInt64())
	}
	if len(data.RedistributeRoutes) > 0 {
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipPrimaryKey", []string{"protocol"})
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipValue", []interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipType", "ignore")
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipPrimaryKey", []string{"protocol"})
		body, _ = sjson.Set(body, path+"ospf.redistribute."+"vipValue", []interface{}{})
	}
	for _, item := range data.RedistributeRoutes {
		itemBody := ""
		itemAttributes := make([]string, 0)
		itemAttributes = append(itemAttributes, "protocol")

		if !item.ProtocolVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "protocol."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "protocol."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "protocol."+"vipVariableName", item.ProtocolVariable.ValueString())
		} else if item.Protocol.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "protocol."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "protocol."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "protocol."+"vipValue", item.Protocol.ValueString())
		}
		itemAttributes = append(itemAttributes, "route-policy")

		if !item.RoutePolicyVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipVariableName", item.RoutePolicyVariable.ValueString())
		} else if item.RoutePolicy.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "route-policy."+"vipValue", item.RoutePolicy.ValueString())
		}
		if !item.Optional.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "vipOptional", item.Optional.ValueBool())
			itemBody, _ = sjson.Set(itemBody, "priority-order", itemAttributes)
		}
		body, _ = sjson.SetRaw(body, path+"ospf.redistribute."+"vipValue.-1", itemBody)
	}
	if len(data.RouterLsa) > 0 {
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipPrimaryKey", []string{"ad-type"})
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipValue", []interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipType", "ignore")
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipPrimaryKey", []string{"ad-type"})
		body, _ = sjson.Set(body, path+"ospf.max-metric.router-lsa."+"vipValue", []interface{}{})
	}
	for _, item := range data.RouterLsa {
		itemBody := ""
		itemAttributes := make([]string, 0)
		itemAttributes = append(itemAttributes, "ad-type")
		if item.Type.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "ad-type."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "ad-type."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "ad-type."+"vipValue", item.Type.ValueString())
		}
		itemAttributes = append(itemAttributes, "time")

		if !item.AdvertizementTimeVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "time."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "time."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "time."+"vipVariableName", item.AdvertizementTimeVariable.ValueString())
		} else if item.AdvertizementTime.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "time."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "time."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "time."+"vipValue", item.AdvertizementTime.ValueInt64())
		}
		if !item.Optional.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "vipOptional", item.Optional.ValueBool())
			itemBody, _ = sjson.Set(itemBody, "priority-order", itemAttributes)
		}
		body, _ = sjson.SetRaw(body, path+"ospf.max-metric.router-lsa."+"vipValue.-1", itemBody)
	}
	if len(data.RoutePolicies) > 0 {
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipPrimaryKey", []string{"direction"})
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipValue", []interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipType", "ignore")
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipPrimaryKey", []string{"direction"})
		body, _ = sjson.Set(body, path+"ospf.route-policy."+"vipValue", []interface{}{})
	}
	for _, item := range data.RoutePolicies {
		itemBody := ""
		itemAttributes := make([]string, 0)
		itemAttributes = append(itemAttributes, "direction")

		if !item.DirectionVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "direction."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "direction."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "direction."+"vipVariableName", item.DirectionVariable.ValueString())
		} else if item.Direction.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "direction."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "direction."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "direction."+"vipValue", item.Direction.ValueString())
		}
		itemAttributes = append(itemAttributes, "pol-name")

		if !item.PolicyNameVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "pol-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "pol-name."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "pol-name."+"vipVariableName", item.PolicyNameVariable.ValueString())
		} else if item.PolicyName.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "pol-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "pol-name."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "pol-name."+"vipValue", item.PolicyName.ValueString())
		}
		if !item.Optional.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "vipOptional", item.Optional.ValueBool())
			itemBody, _ = sjson.Set(itemBody, "priority-order", itemAttributes)
		}
		body, _ = sjson.SetRaw(body, path+"ospf.route-policy."+"vipValue.-1", itemBody)
	}
	if len(data.OspfArea) > 0 {
		body, _ = sjson.Set(body, path+"ospf.area."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.area."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ospf.area."+"vipPrimaryKey", []string{"a-num"})
		body, _ = sjson.Set(body, path+"ospf.area."+"vipValue", []interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"ospf.area."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"ospf.area."+"vipType", "ignore")
		body, _ = sjson.Set(body, path+"ospf.area."+"vipPrimaryKey", []string{"a-num"})
		body, _ = sjson.Set(body, path+"ospf.area."+"vipValue", []interface{}{})
	}
	for _, item := range data.OspfArea {
		itemBody := ""
		itemAttributes := make([]string, 0)
		itemAttributes = append(itemAttributes, "a-num")

		if !item.AreaNumberVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "a-num."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "a-num."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "a-num."+"vipVariableName", item.AreaNumberVariable.ValueString())
		} else if item.AreaNumber.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "a-num."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "a-num."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "a-num."+"vipValue", item.AreaNumber.ValueInt64())
		}
		itemAttributes = append(itemAttributes, "no-summary")

		if !item.StubNoSummaryVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipObjectType", "node-only")
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipVariableName", item.StubNoSummaryVariable.ValueString())
		} else if item.StubNoSummary.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipObjectType", "node-only")
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipObjectType", "node-only")
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "stub.no-summary."+"vipValue", strconv.FormatBool(item.StubNoSummary.ValueBool()))
		}
		itemAttributes = append(itemAttributes, "translate")

		if !item.TranslateVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipVariableName", item.TranslateVariable.ValueString())
		} else if item.Translate.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "nssa.translate."+"vipValue", item.Translate.ValueString())
		}
		itemAttributes = append(itemAttributes, "no-summary")

		if !item.NssaNoSummaryVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipObjectType", "node-only")
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipVariableName", item.NssaNoSummaryVariable.ValueString())
		} else if item.NssaNoSummary.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipObjectType", "node-only")
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipObjectType", "node-only")
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "nssa.no-summary."+"vipValue", strconv.FormatBool(item.NssaNoSummary.ValueBool()))
		}
		itemAttributes = append(itemAttributes, "interface")
		if len(item.OspfInterface) > 0 {
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipObjectType", "tree")
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipPrimaryKey", []string{"name"})
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipValue", []interface{}{})
		} else {
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipObjectType", "tree")
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipType", "ignore")
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipPrimaryKey", []string{"name"})
			itemBody, _ = sjson.Set(itemBody, "interface."+"vipValue", []interface{}{})
		}
		for _, childItem := range item.OspfInterface {
			itemChildBody := ""
			itemChildAttributes := make([]string, 0)
			itemChildAttributes = append(itemChildAttributes, "name")

			if !childItem.InterfaceNameVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "name."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "name."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "name."+"vipVariableName", childItem.InterfaceNameVariable.ValueString())
			} else if childItem.InterfaceName.IsNull() {
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "name."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "name."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "name."+"vipValue", childItem.InterfaceName.ValueString())
			}
			itemChildAttributes = append(itemChildAttributes, "hello-interval")

			if !childItem.HelloIntervalVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipVariableName", childItem.HelloIntervalVariable.ValueString())
			} else if childItem.HelloInterval.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "hello-interval."+"vipValue", childItem.HelloInterval.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "dead-interval")

			if !childItem.DeadIntervalVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipVariableName", childItem.DeadIntervalVariable.ValueString())
			} else if childItem.DeadInterval.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "dead-interval."+"vipValue", childItem.DeadInterval.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "retransmit-interval")

			if !childItem.RetransmitIntervalVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipVariableName", childItem.RetransmitIntervalVariable.ValueString())
			} else if childItem.RetransmitInterval.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "retransmit-interval."+"vipValue", childItem.RetransmitInterval.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "cost")

			if !childItem.InterfaceCostVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipVariableName", childItem.InterfaceCostVariable.ValueString())
			} else if childItem.InterfaceCost.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipValue", childItem.InterfaceCost.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "priority")

			if !childItem.DesignatedRouterPriorityVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipVariableName", childItem.DesignatedRouterPriorityVariable.ValueString())
			} else if childItem.DesignatedRouterPriority.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "priority."+"vipValue", childItem.DesignatedRouterPriority.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "network")

			if !childItem.OspfNetworkTypeVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipVariableName", childItem.OspfNetworkTypeVariable.ValueString())
			} else if childItem.OspfNetworkType.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "network."+"vipValue", childItem.OspfNetworkType.ValueString())
			}
			itemChildAttributes = append(itemChildAttributes, "passive-interface")

			if !childItem.PassiveInterfaceVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipObjectType", "node-only")
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipVariableName", childItem.PassiveInterfaceVariable.ValueString())
			} else if childItem.PassiveInterface.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipObjectType", "node-only")
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipObjectType", "node-only")
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "passive-interface."+"vipValue", strconv.FormatBool(childItem.PassiveInterface.ValueBool()))
			}
			itemChildAttributes = append(itemChildAttributes, "type")

			if !childItem.AuthenticationTypeVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipVariableName", childItem.AuthenticationTypeVariable.ValueString())
			} else if childItem.AuthenticationType.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.type."+"vipValue", childItem.AuthenticationType.ValueString())
			}
			itemChildAttributes = append(itemChildAttributes, "authentication-key")

			if !childItem.AuthenticationKeyVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipVariableName", childItem.AuthenticationKeyVariable.ValueString())
			} else if childItem.AuthenticationKey.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.authentication-key."+"vipValue", childItem.AuthenticationKey.ValueString())
			}
			itemChildAttributes = append(itemChildAttributes, "message-digest-key")

			if !childItem.MessageDigestKeyIdVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipVariableName", childItem.MessageDigestKeyIdVariable.ValueString())
			} else if childItem.MessageDigestKeyId.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.message-digest-key."+"vipValue", childItem.MessageDigestKeyId.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "md5")

			if !childItem.MessageDigestKeyVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipVariableName", childItem.MessageDigestKeyVariable.ValueString())
			} else if childItem.MessageDigestKey.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "authentication.message-digest.md5."+"vipValue", childItem.MessageDigestKey.ValueString())
			}
			if !childItem.Optional.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "vipOptional", childItem.Optional.ValueBool())
				itemChildBody, _ = sjson.Set(itemChildBody, "priority-order", itemChildAttributes)
			}
			itemBody, _ = sjson.SetRaw(itemBody, "interface."+"vipValue.-1", itemChildBody)
		}
		itemAttributes = append(itemAttributes, "range")
		if len(item.SummarizeRoutes) > 0 {
			itemBody, _ = sjson.Set(itemBody, "range."+"vipObjectType", "tree")
			itemBody, _ = sjson.Set(itemBody, "range."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "range."+"vipPrimaryKey", []string{"address"})
			itemBody, _ = sjson.Set(itemBody, "range."+"vipValue", []interface{}{})
		} else {
			itemBody, _ = sjson.Set(itemBody, "range."+"vipObjectType", "tree")
			itemBody, _ = sjson.Set(itemBody, "range."+"vipType", "ignore")
			itemBody, _ = sjson.Set(itemBody, "range."+"vipPrimaryKey", []string{"address"})
			itemBody, _ = sjson.Set(itemBody, "range."+"vipValue", []interface{}{})
		}
		for _, childItem := range item.SummarizeRoutes {
			itemChildBody := ""
			itemChildAttributes := make([]string, 0)
			itemChildAttributes = append(itemChildAttributes, "address")

			if !childItem.AddressVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "address."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "address."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "address."+"vipVariableName", childItem.AddressVariable.ValueString())
			} else if childItem.Address.IsNull() {
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "address."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "address."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "address."+"vipValue", childItem.Address.ValueString())
			}
			itemChildAttributes = append(itemChildAttributes, "cost")

			if !childItem.CostVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipVariableName", childItem.CostVariable.ValueString())
			} else if childItem.Cost.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "cost."+"vipValue", childItem.Cost.ValueInt64())
			}
			itemChildAttributes = append(itemChildAttributes, "no-advertise")

			if !childItem.NoAdvertiseVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipObjectType", "node-only")
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipVariableName", childItem.NoAdvertiseVariable.ValueString())
			} else if childItem.NoAdvertise.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipObjectType", "node-only")
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipType", "ignore")
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipObjectType", "node-only")
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "no-advertise."+"vipValue", strconv.FormatBool(childItem.NoAdvertise.ValueBool()))
			}
			if !childItem.Optional.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "vipOptional", childItem.Optional.ValueBool())
				itemChildBody, _ = sjson.Set(itemChildBody, "priority-order", itemChildAttributes)
			}
			itemBody, _ = sjson.SetRaw(itemBody, "range."+"vipValue.-1", itemChildBody)
		}
		if !item.Optional.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "vipOptional", item.Optional.ValueBool())
			itemBody, _ = sjson.Set(itemBody, "priority-order", itemAttributes)
		}
		body, _ = sjson.SetRaw(body, path+"ospf.area."+"vipValue.-1", itemBody)
	}
	return body
}

func (data *Ospf) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("deviceType"); value.Exists() {
		data.DeviceTypes = helpers.GetStringSet(value.Array())
	} else {
		data.DeviceTypes = types.SetNull(types.StringType)
	}
	if value := res.Get("templateDescription"); value.Exists() && value.String() != "" {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("templateName"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("templateType"); value.Exists() {
		data.TemplateType = types.StringValue(value.String())
	} else {
		data.TemplateType = types.StringNull()
	}

	path := "templateDefinition."
	if value := res.Get(path + "ospf.router-id.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.RouterId = types.StringNull()

			v := res.Get(path + "ospf.router-id.vipVariableName")
			data.RouterIdVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.RouterId = types.StringNull()
			data.RouterIdVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.router-id.vipValue")
			data.RouterId = types.StringValue(v.String())
			data.RouterIdVariable = types.StringNull()
		}
	} else {
		data.RouterId = types.StringNull()
		data.RouterIdVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.auto-cost.reference-bandwidth.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.ReferenceBandwidth = types.Int64Null()

			v := res.Get(path + "ospf.auto-cost.reference-bandwidth.vipVariableName")
			data.ReferenceBandwidthVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.ReferenceBandwidth = types.Int64Null()
			data.ReferenceBandwidthVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.auto-cost.reference-bandwidth.vipValue")
			data.ReferenceBandwidth = types.Int64Value(v.Int())
			data.ReferenceBandwidthVariable = types.StringNull()
		}
	} else {
		data.ReferenceBandwidth = types.Int64Null()
		data.ReferenceBandwidthVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.compatible.rfc1583.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.Rfc1583Compatible = types.BoolNull()

			v := res.Get(path + "ospf.compatible.rfc1583.vipVariableName")
			data.Rfc1583CompatibleVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.Rfc1583Compatible = types.BoolNull()
			data.Rfc1583CompatibleVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.compatible.rfc1583.vipValue")
			data.Rfc1583Compatible = types.BoolValue(v.Bool())
			data.Rfc1583CompatibleVariable = types.StringNull()
		}
	} else {
		data.Rfc1583Compatible = types.BoolNull()
		data.Rfc1583CompatibleVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.default-information.originate.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.OriginateDefaultRoute = types.BoolNull()

		} else if value.String() == "ignore" {
			data.OriginateDefaultRoute = types.BoolNull()

		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.default-information.originate.vipValue")
			data.OriginateDefaultRoute = types.BoolValue(v.Bool())

		}
	} else {
		data.OriginateDefaultRoute = types.BoolNull()

	}
	if value := res.Get(path + "ospf.default-information.originate.always.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.Always = types.BoolNull()

			v := res.Get(path + "ospf.default-information.originate.always.vipVariableName")
			data.AlwaysVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.Always = types.BoolNull()
			data.AlwaysVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.default-information.originate.always.vipValue")
			data.Always = types.BoolValue(v.Bool())
			data.AlwaysVariable = types.StringNull()
		}
	} else {
		data.Always = types.BoolNull()
		data.AlwaysVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.default-information.originate.metric.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.DefaultMetric = types.Int64Null()

			v := res.Get(path + "ospf.default-information.originate.metric.vipVariableName")
			data.DefaultMetricVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.DefaultMetric = types.Int64Null()
			data.DefaultMetricVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.default-information.originate.metric.vipValue")
			data.DefaultMetric = types.Int64Value(v.Int())
			data.DefaultMetricVariable = types.StringNull()
		}
	} else {
		data.DefaultMetric = types.Int64Null()
		data.DefaultMetricVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.default-information.originate.metric-type.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.MetricType = types.StringNull()

			v := res.Get(path + "ospf.default-information.originate.metric-type.vipVariableName")
			data.MetricTypeVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.MetricType = types.StringNull()
			data.MetricTypeVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.default-information.originate.metric-type.vipValue")
			data.MetricType = types.StringValue(v.String())
			data.MetricTypeVariable = types.StringNull()
		}
	} else {
		data.MetricType = types.StringNull()
		data.MetricTypeVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.distance.external.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.DistanceForExternalRoutes = types.Int64Null()

			v := res.Get(path + "ospf.distance.external.vipVariableName")
			data.DistanceForExternalRoutesVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.DistanceForExternalRoutes = types.Int64Null()
			data.DistanceForExternalRoutesVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.distance.external.vipValue")
			data.DistanceForExternalRoutes = types.Int64Value(v.Int())
			data.DistanceForExternalRoutesVariable = types.StringNull()
		}
	} else {
		data.DistanceForExternalRoutes = types.Int64Null()
		data.DistanceForExternalRoutesVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.distance.inter-area.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.DistanceForInterAreaRoutes = types.Int64Null()

			v := res.Get(path + "ospf.distance.inter-area.vipVariableName")
			data.DistanceForInterAreaRoutesVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.DistanceForInterAreaRoutes = types.Int64Null()
			data.DistanceForInterAreaRoutesVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.distance.inter-area.vipValue")
			data.DistanceForInterAreaRoutes = types.Int64Value(v.Int())
			data.DistanceForInterAreaRoutesVariable = types.StringNull()
		}
	} else {
		data.DistanceForInterAreaRoutes = types.Int64Null()
		data.DistanceForInterAreaRoutesVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.distance.intra-area.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.DistanceForIntraAreaRoutes = types.Int64Null()

			v := res.Get(path + "ospf.distance.intra-area.vipVariableName")
			data.DistanceForIntraAreaRoutesVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.DistanceForIntraAreaRoutes = types.Int64Null()
			data.DistanceForIntraAreaRoutesVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.distance.intra-area.vipValue")
			data.DistanceForIntraAreaRoutes = types.Int64Value(v.Int())
			data.DistanceForIntraAreaRoutesVariable = types.StringNull()
		}
	} else {
		data.DistanceForIntraAreaRoutes = types.Int64Null()
		data.DistanceForIntraAreaRoutesVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.timers.spf.delay.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.SpfCalculationDelay = types.Int64Null()

			v := res.Get(path + "ospf.timers.spf.delay.vipVariableName")
			data.SpfCalculationDelayVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.SpfCalculationDelay = types.Int64Null()
			data.SpfCalculationDelayVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.timers.spf.delay.vipValue")
			data.SpfCalculationDelay = types.Int64Value(v.Int())
			data.SpfCalculationDelayVariable = types.StringNull()
		}
	} else {
		data.SpfCalculationDelay = types.Int64Null()
		data.SpfCalculationDelayVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.timers.spf.initial-hold.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.InitialHoldTime = types.Int64Null()

			v := res.Get(path + "ospf.timers.spf.initial-hold.vipVariableName")
			data.InitialHoldTimeVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.InitialHoldTime = types.Int64Null()
			data.InitialHoldTimeVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.timers.spf.initial-hold.vipValue")
			data.InitialHoldTime = types.Int64Value(v.Int())
			data.InitialHoldTimeVariable = types.StringNull()
		}
	} else {
		data.InitialHoldTime = types.Int64Null()
		data.InitialHoldTimeVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.timers.spf.max-hold.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.MaxHoldTime = types.Int64Null()

			v := res.Get(path + "ospf.timers.spf.max-hold.vipVariableName")
			data.MaxHoldTimeVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.MaxHoldTime = types.Int64Null()
			data.MaxHoldTimeVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ospf.timers.spf.max-hold.vipValue")
			data.MaxHoldTime = types.Int64Value(v.Int())
			data.MaxHoldTimeVariable = types.StringNull()
		}
	} else {
		data.MaxHoldTime = types.Int64Null()
		data.MaxHoldTimeVariable = types.StringNull()
	}
	if value := res.Get(path + "ospf.redistribute.vipValue"); len(value.Array()) > 0 {
		data.RedistributeRoutes = make([]OspfRedistributeRoutes, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := OspfRedistributeRoutes{}
			if cValue := v.Get("vipOptional"); cValue.Exists() {
				item.Optional = types.BoolValue(cValue.Bool())
			} else {
				item.Optional = types.BoolNull()
			}
			if cValue := v.Get("protocol.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.Protocol = types.StringNull()

					cv := v.Get("protocol.vipVariableName")
					item.ProtocolVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.Protocol = types.StringNull()
					item.ProtocolVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("protocol.vipValue")
					item.Protocol = types.StringValue(cv.String())
					item.ProtocolVariable = types.StringNull()
				}
			} else {
				item.Protocol = types.StringNull()
				item.ProtocolVariable = types.StringNull()
			}
			if cValue := v.Get("route-policy.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.RoutePolicy = types.StringNull()

					cv := v.Get("route-policy.vipVariableName")
					item.RoutePolicyVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.RoutePolicy = types.StringNull()
					item.RoutePolicyVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("route-policy.vipValue")
					item.RoutePolicy = types.StringValue(cv.String())
					item.RoutePolicyVariable = types.StringNull()
				}
			} else {
				item.RoutePolicy = types.StringNull()
				item.RoutePolicyVariable = types.StringNull()
			}
			data.RedistributeRoutes = append(data.RedistributeRoutes, item)
			return true
		})
	}
	if value := res.Get(path + "ospf.max-metric.router-lsa.vipValue"); len(value.Array()) > 0 {
		data.RouterLsa = make([]OspfRouterLsa, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := OspfRouterLsa{}
			if cValue := v.Get("vipOptional"); cValue.Exists() {
				item.Optional = types.BoolValue(cValue.Bool())
			} else {
				item.Optional = types.BoolNull()
			}
			if cValue := v.Get("ad-type.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.Type = types.StringNull()

				} else if cValue.String() == "ignore" {
					item.Type = types.StringNull()

				} else if cValue.String() == "constant" {
					cv := v.Get("ad-type.vipValue")
					item.Type = types.StringValue(cv.String())

				}
			} else {
				item.Type = types.StringNull()

			}
			if cValue := v.Get("time.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.AdvertizementTime = types.Int64Null()

					cv := v.Get("time.vipVariableName")
					item.AdvertizementTimeVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.AdvertizementTime = types.Int64Null()
					item.AdvertizementTimeVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("time.vipValue")
					item.AdvertizementTime = types.Int64Value(cv.Int())
					item.AdvertizementTimeVariable = types.StringNull()
				}
			} else {
				item.AdvertizementTime = types.Int64Null()
				item.AdvertizementTimeVariable = types.StringNull()
			}
			data.RouterLsa = append(data.RouterLsa, item)
			return true
		})
	}
	if value := res.Get(path + "ospf.route-policy.vipValue"); len(value.Array()) > 0 {
		data.RoutePolicies = make([]OspfRoutePolicies, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := OspfRoutePolicies{}
			if cValue := v.Get("vipOptional"); cValue.Exists() {
				item.Optional = types.BoolValue(cValue.Bool())
			} else {
				item.Optional = types.BoolNull()
			}
			if cValue := v.Get("direction.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.Direction = types.StringNull()

					cv := v.Get("direction.vipVariableName")
					item.DirectionVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.Direction = types.StringNull()
					item.DirectionVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("direction.vipValue")
					item.Direction = types.StringValue(cv.String())
					item.DirectionVariable = types.StringNull()
				}
			} else {
				item.Direction = types.StringNull()
				item.DirectionVariable = types.StringNull()
			}
			if cValue := v.Get("pol-name.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.PolicyName = types.StringNull()

					cv := v.Get("pol-name.vipVariableName")
					item.PolicyNameVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.PolicyName = types.StringNull()
					item.PolicyNameVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("pol-name.vipValue")
					item.PolicyName = types.StringValue(cv.String())
					item.PolicyNameVariable = types.StringNull()
				}
			} else {
				item.PolicyName = types.StringNull()
				item.PolicyNameVariable = types.StringNull()
			}
			data.RoutePolicies = append(data.RoutePolicies, item)
			return true
		})
	}
	if value := res.Get(path + "ospf.area.vipValue"); len(value.Array()) > 0 {
		data.OspfArea = make([]OspfOspfArea, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := OspfOspfArea{}
			if cValue := v.Get("vipOptional"); cValue.Exists() {
				item.Optional = types.BoolValue(cValue.Bool())
			} else {
				item.Optional = types.BoolNull()
			}
			if cValue := v.Get("a-num.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.AreaNumber = types.Int64Null()

					cv := v.Get("a-num.vipVariableName")
					item.AreaNumberVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.AreaNumber = types.Int64Null()
					item.AreaNumberVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("a-num.vipValue")
					item.AreaNumber = types.Int64Value(cv.Int())
					item.AreaNumberVariable = types.StringNull()
				}
			} else {
				item.AreaNumber = types.Int64Null()
				item.AreaNumberVariable = types.StringNull()
			}
			if cValue := v.Get("stub.no-summary.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.StubNoSummary = types.BoolNull()

					cv := v.Get("stub.no-summary.vipVariableName")
					item.StubNoSummaryVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.StubNoSummary = types.BoolNull()
					item.StubNoSummaryVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("stub.no-summary.vipValue")
					item.StubNoSummary = types.BoolValue(cv.Bool())
					item.StubNoSummaryVariable = types.StringNull()
				}
			} else {
				item.StubNoSummary = types.BoolNull()
				item.StubNoSummaryVariable = types.StringNull()
			}
			if cValue := v.Get("nssa.translate.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.Translate = types.StringNull()

					cv := v.Get("nssa.translate.vipVariableName")
					item.TranslateVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.Translate = types.StringNull()
					item.TranslateVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("nssa.translate.vipValue")
					item.Translate = types.StringValue(cv.String())
					item.TranslateVariable = types.StringNull()
				}
			} else {
				item.Translate = types.StringNull()
				item.TranslateVariable = types.StringNull()
			}
			if cValue := v.Get("nssa.no-summary.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.NssaNoSummary = types.BoolNull()

					cv := v.Get("nssa.no-summary.vipVariableName")
					item.NssaNoSummaryVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.NssaNoSummary = types.BoolNull()
					item.NssaNoSummaryVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("nssa.no-summary.vipValue")
					item.NssaNoSummary = types.BoolValue(cv.Bool())
					item.NssaNoSummaryVariable = types.StringNull()
				}
			} else {
				item.NssaNoSummary = types.BoolNull()
				item.NssaNoSummaryVariable = types.StringNull()
			}
			if cValue := v.Get("interface.vipValue"); len(cValue.Array()) > 0 {
				item.OspfInterface = make([]OspfOspfAreaOspfInterface, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := OspfOspfAreaOspfInterface{}
					if ccValue := cv.Get("vipOptional"); ccValue.Exists() {
						cItem.Optional = types.BoolValue(ccValue.Bool())
					} else {
						cItem.Optional = types.BoolNull()
					}
					if ccValue := cv.Get("name.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.InterfaceName = types.StringNull()

							ccv := cv.Get("name.vipVariableName")
							cItem.InterfaceNameVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.InterfaceName = types.StringNull()
							cItem.InterfaceNameVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("name.vipValue")
							cItem.InterfaceName = types.StringValue(ccv.String())
							cItem.InterfaceNameVariable = types.StringNull()
						}
					} else {
						cItem.InterfaceName = types.StringNull()
						cItem.InterfaceNameVariable = types.StringNull()
					}
					if ccValue := cv.Get("hello-interval.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.HelloInterval = types.Int64Null()

							ccv := cv.Get("hello-interval.vipVariableName")
							cItem.HelloIntervalVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.HelloInterval = types.Int64Null()
							cItem.HelloIntervalVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("hello-interval.vipValue")
							cItem.HelloInterval = types.Int64Value(ccv.Int())
							cItem.HelloIntervalVariable = types.StringNull()
						}
					} else {
						cItem.HelloInterval = types.Int64Null()
						cItem.HelloIntervalVariable = types.StringNull()
					}
					if ccValue := cv.Get("dead-interval.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.DeadInterval = types.Int64Null()

							ccv := cv.Get("dead-interval.vipVariableName")
							cItem.DeadIntervalVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.DeadInterval = types.Int64Null()
							cItem.DeadIntervalVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("dead-interval.vipValue")
							cItem.DeadInterval = types.Int64Value(ccv.Int())
							cItem.DeadIntervalVariable = types.StringNull()
						}
					} else {
						cItem.DeadInterval = types.Int64Null()
						cItem.DeadIntervalVariable = types.StringNull()
					}
					if ccValue := cv.Get("retransmit-interval.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.RetransmitInterval = types.Int64Null()

							ccv := cv.Get("retransmit-interval.vipVariableName")
							cItem.RetransmitIntervalVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.RetransmitInterval = types.Int64Null()
							cItem.RetransmitIntervalVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("retransmit-interval.vipValue")
							cItem.RetransmitInterval = types.Int64Value(ccv.Int())
							cItem.RetransmitIntervalVariable = types.StringNull()
						}
					} else {
						cItem.RetransmitInterval = types.Int64Null()
						cItem.RetransmitIntervalVariable = types.StringNull()
					}
					if ccValue := cv.Get("cost.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.InterfaceCost = types.Int64Null()

							ccv := cv.Get("cost.vipVariableName")
							cItem.InterfaceCostVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.InterfaceCost = types.Int64Null()
							cItem.InterfaceCostVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("cost.vipValue")
							cItem.InterfaceCost = types.Int64Value(ccv.Int())
							cItem.InterfaceCostVariable = types.StringNull()
						}
					} else {
						cItem.InterfaceCost = types.Int64Null()
						cItem.InterfaceCostVariable = types.StringNull()
					}
					if ccValue := cv.Get("priority.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.DesignatedRouterPriority = types.Int64Null()

							ccv := cv.Get("priority.vipVariableName")
							cItem.DesignatedRouterPriorityVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.DesignatedRouterPriority = types.Int64Null()
							cItem.DesignatedRouterPriorityVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("priority.vipValue")
							cItem.DesignatedRouterPriority = types.Int64Value(ccv.Int())
							cItem.DesignatedRouterPriorityVariable = types.StringNull()
						}
					} else {
						cItem.DesignatedRouterPriority = types.Int64Null()
						cItem.DesignatedRouterPriorityVariable = types.StringNull()
					}
					if ccValue := cv.Get("network.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.OspfNetworkType = types.StringNull()

							ccv := cv.Get("network.vipVariableName")
							cItem.OspfNetworkTypeVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.OspfNetworkType = types.StringNull()
							cItem.OspfNetworkTypeVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("network.vipValue")
							cItem.OspfNetworkType = types.StringValue(ccv.String())
							cItem.OspfNetworkTypeVariable = types.StringNull()
						}
					} else {
						cItem.OspfNetworkType = types.StringNull()
						cItem.OspfNetworkTypeVariable = types.StringNull()
					}
					if ccValue := cv.Get("passive-interface.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.PassiveInterface = types.BoolNull()

							ccv := cv.Get("passive-interface.vipVariableName")
							cItem.PassiveInterfaceVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.PassiveInterface = types.BoolNull()
							cItem.PassiveInterfaceVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("passive-interface.vipValue")
							cItem.PassiveInterface = types.BoolValue(ccv.Bool())
							cItem.PassiveInterfaceVariable = types.StringNull()
						}
					} else {
						cItem.PassiveInterface = types.BoolNull()
						cItem.PassiveInterfaceVariable = types.StringNull()
					}
					if ccValue := cv.Get("authentication.type.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.AuthenticationType = types.StringNull()

							ccv := cv.Get("authentication.type.vipVariableName")
							cItem.AuthenticationTypeVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.AuthenticationType = types.StringNull()
							cItem.AuthenticationTypeVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("authentication.type.vipValue")
							cItem.AuthenticationType = types.StringValue(ccv.String())
							cItem.AuthenticationTypeVariable = types.StringNull()
						}
					} else {
						cItem.AuthenticationType = types.StringNull()
						cItem.AuthenticationTypeVariable = types.StringNull()
					}
					if ccValue := cv.Get("authentication.authentication-key.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.AuthenticationKey = types.StringNull()

							ccv := cv.Get("authentication.authentication-key.vipVariableName")
							cItem.AuthenticationKeyVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.AuthenticationKey = types.StringNull()
							cItem.AuthenticationKeyVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("authentication.authentication-key.vipValue")
							cItem.AuthenticationKey = types.StringValue(ccv.String())
							cItem.AuthenticationKeyVariable = types.StringNull()
						}
					} else {
						cItem.AuthenticationKey = types.StringNull()
						cItem.AuthenticationKeyVariable = types.StringNull()
					}
					if ccValue := cv.Get("authentication.message-digest.message-digest-key.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.MessageDigestKeyId = types.Int64Null()

							ccv := cv.Get("authentication.message-digest.message-digest-key.vipVariableName")
							cItem.MessageDigestKeyIdVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.MessageDigestKeyId = types.Int64Null()
							cItem.MessageDigestKeyIdVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("authentication.message-digest.message-digest-key.vipValue")
							cItem.MessageDigestKeyId = types.Int64Value(ccv.Int())
							cItem.MessageDigestKeyIdVariable = types.StringNull()
						}
					} else {
						cItem.MessageDigestKeyId = types.Int64Null()
						cItem.MessageDigestKeyIdVariable = types.StringNull()
					}
					if ccValue := cv.Get("authentication.message-digest.md5.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.MessageDigestKey = types.StringNull()

							ccv := cv.Get("authentication.message-digest.md5.vipVariableName")
							cItem.MessageDigestKeyVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.MessageDigestKey = types.StringNull()
							cItem.MessageDigestKeyVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("authentication.message-digest.md5.vipValue")
							cItem.MessageDigestKey = types.StringValue(ccv.String())
							cItem.MessageDigestKeyVariable = types.StringNull()
						}
					} else {
						cItem.MessageDigestKey = types.StringNull()
						cItem.MessageDigestKeyVariable = types.StringNull()
					}
					item.OspfInterface = append(item.OspfInterface, cItem)
					return true
				})
			}
			if cValue := v.Get("range.vipValue"); len(cValue.Array()) > 0 {
				item.SummarizeRoutes = make([]OspfOspfAreaSummarizeRoutes, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := OspfOspfAreaSummarizeRoutes{}
					if ccValue := cv.Get("vipOptional"); ccValue.Exists() {
						cItem.Optional = types.BoolValue(ccValue.Bool())
					} else {
						cItem.Optional = types.BoolNull()
					}
					if ccValue := cv.Get("address.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.Address = types.StringNull()

							ccv := cv.Get("address.vipVariableName")
							cItem.AddressVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.Address = types.StringNull()
							cItem.AddressVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("address.vipValue")
							cItem.Address = types.StringValue(ccv.String())
							cItem.AddressVariable = types.StringNull()
						}
					} else {
						cItem.Address = types.StringNull()
						cItem.AddressVariable = types.StringNull()
					}
					if ccValue := cv.Get("cost.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.Cost = types.Int64Null()

							ccv := cv.Get("cost.vipVariableName")
							cItem.CostVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.Cost = types.Int64Null()
							cItem.CostVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("cost.vipValue")
							cItem.Cost = types.Int64Value(ccv.Int())
							cItem.CostVariable = types.StringNull()
						}
					} else {
						cItem.Cost = types.Int64Null()
						cItem.CostVariable = types.StringNull()
					}
					if ccValue := cv.Get("no-advertise.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.NoAdvertise = types.BoolNull()

							ccv := cv.Get("no-advertise.vipVariableName")
							cItem.NoAdvertiseVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.NoAdvertise = types.BoolNull()
							cItem.NoAdvertiseVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("no-advertise.vipValue")
							cItem.NoAdvertise = types.BoolValue(ccv.Bool())
							cItem.NoAdvertiseVariable = types.StringNull()
						}
					} else {
						cItem.NoAdvertise = types.BoolNull()
						cItem.NoAdvertiseVariable = types.StringNull()
					}
					item.SummarizeRoutes = append(item.SummarizeRoutes, cItem)
					return true
				})
			}
			data.OspfArea = append(data.OspfArea, item)
			return true
		})
	}
}

func (data *Ospf) hasChanges(ctx context.Context, state *Ospf) bool {
	hasChanges := false
	if !data.RouterId.Equal(state.RouterId) {
		hasChanges = true
	}
	if !data.ReferenceBandwidth.Equal(state.ReferenceBandwidth) {
		hasChanges = true
	}
	if !data.Rfc1583Compatible.Equal(state.Rfc1583Compatible) {
		hasChanges = true
	}
	if !data.OriginateDefaultRoute.Equal(state.OriginateDefaultRoute) {
		hasChanges = true
	}
	if !data.Always.Equal(state.Always) {
		hasChanges = true
	}
	if !data.DefaultMetric.Equal(state.DefaultMetric) {
		hasChanges = true
	}
	if !data.MetricType.Equal(state.MetricType) {
		hasChanges = true
	}
	if !data.DistanceForExternalRoutes.Equal(state.DistanceForExternalRoutes) {
		hasChanges = true
	}
	if !data.DistanceForInterAreaRoutes.Equal(state.DistanceForInterAreaRoutes) {
		hasChanges = true
	}
	if !data.DistanceForIntraAreaRoutes.Equal(state.DistanceForIntraAreaRoutes) {
		hasChanges = true
	}
	if !data.SpfCalculationDelay.Equal(state.SpfCalculationDelay) {
		hasChanges = true
	}
	if !data.InitialHoldTime.Equal(state.InitialHoldTime) {
		hasChanges = true
	}
	if !data.MaxHoldTime.Equal(state.MaxHoldTime) {
		hasChanges = true
	}
	if len(data.RedistributeRoutes) != len(state.RedistributeRoutes) {
		hasChanges = true
	} else {
		for i := range data.RedistributeRoutes {
			if !data.RedistributeRoutes[i].Protocol.Equal(state.RedistributeRoutes[i].Protocol) {
				hasChanges = true
			}
			if !data.RedistributeRoutes[i].RoutePolicy.Equal(state.RedistributeRoutes[i].RoutePolicy) {
				hasChanges = true
			}
		}
	}
	if len(data.RouterLsa) != len(state.RouterLsa) {
		hasChanges = true
	} else {
		for i := range data.RouterLsa {
			if !data.RouterLsa[i].Type.Equal(state.RouterLsa[i].Type) {
				hasChanges = true
			}
			if !data.RouterLsa[i].AdvertizementTime.Equal(state.RouterLsa[i].AdvertizementTime) {
				hasChanges = true
			}
		}
	}
	if len(data.RoutePolicies) != len(state.RoutePolicies) {
		hasChanges = true
	} else {
		for i := range data.RoutePolicies {
			if !data.RoutePolicies[i].Direction.Equal(state.RoutePolicies[i].Direction) {
				hasChanges = true
			}
			if !data.RoutePolicies[i].PolicyName.Equal(state.RoutePolicies[i].PolicyName) {
				hasChanges = true
			}
		}
	}
	if len(data.OspfArea) != len(state.OspfArea) {
		hasChanges = true
	} else {
		for i := range data.OspfArea {
			if !data.OspfArea[i].AreaNumber.Equal(state.OspfArea[i].AreaNumber) {
				hasChanges = true
			}
			if !data.OspfArea[i].StubNoSummary.Equal(state.OspfArea[i].StubNoSummary) {
				hasChanges = true
			}
			if !data.OspfArea[i].Translate.Equal(state.OspfArea[i].Translate) {
				hasChanges = true
			}
			if !data.OspfArea[i].NssaNoSummary.Equal(state.OspfArea[i].NssaNoSummary) {
				hasChanges = true
			}
			if len(data.OspfArea[i].OspfInterface) != len(state.OspfArea[i].OspfInterface) {
				hasChanges = true
			} else {
				for ii := range data.OspfArea[i].OspfInterface {
					if !data.OspfArea[i].OspfInterface[ii].InterfaceName.Equal(state.OspfArea[i].OspfInterface[ii].InterfaceName) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].HelloInterval.Equal(state.OspfArea[i].OspfInterface[ii].HelloInterval) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].DeadInterval.Equal(state.OspfArea[i].OspfInterface[ii].DeadInterval) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].RetransmitInterval.Equal(state.OspfArea[i].OspfInterface[ii].RetransmitInterval) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].InterfaceCost.Equal(state.OspfArea[i].OspfInterface[ii].InterfaceCost) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].DesignatedRouterPriority.Equal(state.OspfArea[i].OspfInterface[ii].DesignatedRouterPriority) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].OspfNetworkType.Equal(state.OspfArea[i].OspfInterface[ii].OspfNetworkType) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].PassiveInterface.Equal(state.OspfArea[i].OspfInterface[ii].PassiveInterface) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].AuthenticationType.Equal(state.OspfArea[i].OspfInterface[ii].AuthenticationType) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].AuthenticationKey.Equal(state.OspfArea[i].OspfInterface[ii].AuthenticationKey) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].MessageDigestKeyId.Equal(state.OspfArea[i].OspfInterface[ii].MessageDigestKeyId) {
						hasChanges = true
					}
					if !data.OspfArea[i].OspfInterface[ii].MessageDigestKey.Equal(state.OspfArea[i].OspfInterface[ii].MessageDigestKey) {
						hasChanges = true
					}
				}
			}
			if len(data.OspfArea[i].SummarizeRoutes) != len(state.OspfArea[i].SummarizeRoutes) {
				hasChanges = true
			} else {
				for ii := range data.OspfArea[i].SummarizeRoutes {
					if !data.OspfArea[i].SummarizeRoutes[ii].Address.Equal(state.OspfArea[i].SummarizeRoutes[ii].Address) {
						hasChanges = true
					}
					if !data.OspfArea[i].SummarizeRoutes[ii].Cost.Equal(state.OspfArea[i].SummarizeRoutes[ii].Cost) {
						hasChanges = true
					}
					if !data.OspfArea[i].SummarizeRoutes[ii].NoAdvertise.Equal(state.OspfArea[i].SummarizeRoutes[ii].NoAdvertise) {
						hasChanges = true
					}
				}
			}
		}
	}
	return hasChanges
}
