// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Tenant struct {
	Id                     types.String                   `tfsdk:"id"`
	Version                types.Int64                    `tfsdk:"version"`
	TemplateType           types.String                   `tfsdk:"template_type"`
	Name                   types.String                   `tfsdk:"name"`
	Description            types.String                   `tfsdk:"description"`
	DeviceTypes            types.Set                      `tfsdk:"device_types"`
	TenantOrganizationName []TenantTenantOrganizationName `tfsdk:"tenant_organization_name"`
}

type TenantTenantOrganizationName struct {
	Optional                 types.Bool   `tfsdk:"optional"`
	OrganizationName         types.String `tfsdk:"organization_name"`
	OrganizationNameVariable types.String `tfsdk:"organization_name_variable"`
	TierName                 types.String `tfsdk:"tier_name"`
	MaximumVpnsAllowed       types.Int64  `tfsdk:"maximum_vpns_allowed"`
}

func (data Tenant) getModel() string {
	return "tenant"
}

func (data Tenant) toBody(ctx context.Context) string {
	body := ""

	var device_types []string
	data.DeviceTypes.ElementsAs(ctx, &device_types, false)
	body, _ = sjson.Set(body, "deviceType", device_types)
	body, _ = sjson.Set(body, "factoryDefault", false)
	body, _ = sjson.Set(body, "templateDescription", data.Description.ValueString())
	body, _ = sjson.Set(body, "templateMinVersion", "15.0.0")
	body, _ = sjson.Set(body, "templateName", data.Name.ValueString())
	body, _ = sjson.Set(body, "templateType", "tenant")
	body, _ = sjson.Set(body, "templateDefinition", map[string]interface{}{})

	path := "templateDefinition."
	if len(data.TenantOrganizationName) > 0 {
		body, _ = sjson.Set(body, path+"tenant."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"tenant."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"tenant."+"vipPrimaryKey", []string{"org-name"})
		body, _ = sjson.Set(body, path+"tenant."+"vipValue", []interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"tenant."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"tenant."+"vipType", "ignore")
		body, _ = sjson.Set(body, path+"tenant."+"vipPrimaryKey", []string{"org-name"})
		body, _ = sjson.Set(body, path+"tenant."+"vipValue", []interface{}{})
	}
	for _, item := range data.TenantOrganizationName {
		itemBody := ""
		itemAttributes := make([]string, 0)
		itemAttributes = append(itemAttributes, "org-name")

		if !item.OrganizationNameVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "org-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "org-name."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "org-name."+"vipVariableName", item.OrganizationNameVariable.ValueString())
		} else if item.OrganizationName.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "org-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "org-name."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "org-name."+"vipValue", item.OrganizationName.ValueString())
		}
		itemAttributes = append(itemAttributes, "tier-name")
		if item.TierName.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "tier", map[string]interface{}{})
		} else {
			itemBody, _ = sjson.Set(itemBody, "tier.tier-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "tier.tier-name."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "tier.tier-name."+"vipValue", item.TierName.ValueString())
		}
		itemAttributes = append(itemAttributes, "max-vpn")
		if item.MaximumVpnsAllowed.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "tier", map[string]interface{}{})
		} else {
			itemBody, _ = sjson.Set(itemBody, "tier.max-vpn."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "tier.max-vpn."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "tier.max-vpn."+"vipValue", item.MaximumVpnsAllowed.ValueInt64())
		}
		if !item.Optional.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "vipOptional", item.Optional.ValueBool())
			itemBody, _ = sjson.Set(itemBody, "priority-order", itemAttributes)
		}
		body, _ = sjson.SetRaw(body, path+"tenant."+"vipValue.-1", itemBody)
	}
	return body
}

func (data *Tenant) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("deviceType"); value.Exists() {
		data.DeviceTypes = helpers.GetStringSet(value.Array())
	} else {
		data.DeviceTypes = types.SetNull(types.StringType)
	}
	if value := res.Get("templateDescription"); value.Exists() && value.String() != "" {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("templateName"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("templateType"); value.Exists() {
		data.TemplateType = types.StringValue(value.String())
	} else {
		data.TemplateType = types.StringNull()
	}

	path := "templateDefinition."
	if value := res.Get(path + "tenant.vipValue"); len(value.Array()) > 0 {
		data.TenantOrganizationName = make([]TenantTenantOrganizationName, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := TenantTenantOrganizationName{}
			if cValue := v.Get("vipOptional"); cValue.Exists() {
				item.Optional = types.BoolValue(cValue.Bool())
			} else {
				item.Optional = types.BoolNull()
			}
			if cValue := v.Get("org-name.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.OrganizationName = types.StringNull()

					cv := v.Get("org-name.vipVariableName")
					item.OrganizationNameVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.OrganizationName = types.StringNull()
					item.OrganizationNameVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("org-name.vipValue")
					item.OrganizationName = types.StringValue(cv.String())
					item.OrganizationNameVariable = types.StringNull()
				}
			} else {
				item.OrganizationName = types.StringNull()
				item.OrganizationNameVariable = types.StringNull()
			}
			if cValue := v.Get("tier.tier-name.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.TierName = types.StringNull()

				} else if cValue.String() == "ignore" {
					item.TierName = types.StringNull()

				} else if cValue.String() == "constant" {
					cv := v.Get("tier.tier-name.vipValue")
					item.TierName = types.StringValue(cv.String())

				}
			} else {
				item.TierName = types.StringNull()

			}
			if cValue := v.Get("tier.max-vpn.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.MaximumVpnsAllowed = types.Int64Null()

				} else if cValue.String() == "ignore" {
					item.MaximumVpnsAllowed = types.Int64Null()

				} else if cValue.String() == "constant" {
					cv := v.Get("tier.max-vpn.vipValue")
					item.MaximumVpnsAllowed = types.Int64Value(cv.Int())

				}
			} else {
				item.MaximumVpnsAllowed = types.Int64Null()

			}
			data.TenantOrganizationName = append(data.TenantOrganizationName, item)
			return true
		})
	}
}

func (data *Tenant) hasChanges(ctx context.Context, state *Tenant) bool {
	hasChanges := false
	if len(data.TenantOrganizationName) != len(state.TenantOrganizationName) {
		hasChanges = true
	} else {
		for i := range data.TenantOrganizationName {
			if !data.TenantOrganizationName[i].OrganizationName.Equal(state.TenantOrganizationName[i].OrganizationName) {
				hasChanges = true
			}
			if !data.TenantOrganizationName[i].TierName.Equal(state.TenantOrganizationName[i].TierName) {
				hasChanges = true
			}
			if !data.TenantOrganizationName[i].MaximumVpnsAllowed.Equal(state.TenantOrganizationName[i].MaximumVpnsAllowed) {
				hasChanges = true
			}
		}
	}
	return hasChanges
}
