// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Bridge struct {
	Id                              types.String                            `tfsdk:"id"`
	Version                         types.Int64                             `tfsdk:"version"`
	TemplateType                    types.String                            `tfsdk:"template_type"`
	Name                            types.String                            `tfsdk:"name"`
	Description                     types.String                            `tfsdk:"description"`
	DeviceTypes                     types.Set                               `tfsdk:"device_types"`
	BridgeName                      types.String                            `tfsdk:"bridge_name"`
	BridgeNameVariable              types.String                            `tfsdk:"bridge_name_variable"`
	AgeOutTime                      types.Int64                             `tfsdk:"age_out_time"`
	AgeOutTimeVariable              types.String                            `tfsdk:"age_out_time_variable"`
	MaximumMacAddresses             types.Int64                             `tfsdk:"maximum_mac_addresses"`
	MaximumMacAddressesVariable     types.String                            `tfsdk:"maximum_mac_addresses_variable"`
	VlanId                          types.Int64                             `tfsdk:"vlan_id"`
	VlanIdVariable                  types.String                            `tfsdk:"vlan_id_variable"`
	InterfaceToBindToBridgingDomain []BridgeInterfaceToBindToBridgingDomain `tfsdk:"interface_to_bind_to_bridging_domain"`
}

type BridgeInterfaceToBindToBridgingDomain struct {
	Optional                  types.Bool                                              `tfsdk:"optional"`
	InterfaceName             types.String                                            `tfsdk:"interface_name"`
	InterfaceNameVariable     types.String                                            `tfsdk:"interface_name_variable"`
	Description               types.String                                            `tfsdk:"description"`
	DescriptionVariable       types.String                                            `tfsdk:"description_variable"`
	NativeVlanSupport         types.Bool                                              `tfsdk:"native_vlan_support"`
	NativeVlanSupportVariable types.String                                            `tfsdk:"native_vlan_support_variable"`
	StaticMacAddress          []BridgeInterfaceToBindToBridgingDomainStaticMacAddress `tfsdk:"static_mac_address"`
	Shutdown                  types.Bool                                              `tfsdk:"shutdown"`
	ShutdownVariable          types.String                                            `tfsdk:"shutdown_variable"`
}

type BridgeInterfaceToBindToBridgingDomainStaticMacAddress struct {
	Optional           types.Bool   `tfsdk:"optional"`
	MacAddress         types.String `tfsdk:"mac_address"`
	MacAddressVariable types.String `tfsdk:"mac_address_variable"`
}

func (data Bridge) getModel() string {
	return "bridge"
}

func (data Bridge) toBody(ctx context.Context) string {
	body := ""

	var device_types []string
	data.DeviceTypes.ElementsAs(ctx, &device_types, false)
	body, _ = sjson.Set(body, "deviceType", device_types)
	body, _ = sjson.Set(body, "factoryDefault", false)
	body, _ = sjson.Set(body, "templateDescription", data.Description.ValueString())
	body, _ = sjson.Set(body, "templateMinVersion", "15.0.0")
	body, _ = sjson.Set(body, "templateName", data.Name.ValueString())
	body, _ = sjson.Set(body, "templateType", "bridge")
	body, _ = sjson.Set(body, "templateDefinition", map[string]interface{}{})

	path := "templateDefinition."

	if !data.BridgeNameVariable.IsNull() {
		body, _ = sjson.Set(body, path+"name."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"name."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"name."+"vipVariableName", data.BridgeNameVariable.ValueString())
	} else if data.BridgeName.IsNull() {
	} else {
		body, _ = sjson.Set(body, path+"name."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"name."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"name."+"vipValue", data.BridgeName.ValueString())
	}

	if !data.AgeOutTimeVariable.IsNull() {
		body, _ = sjson.Set(body, path+"age-time."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"age-time."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"age-time."+"vipVariableName", data.AgeOutTimeVariable.ValueString())
	} else if data.AgeOutTime.IsNull() {
		body, _ = sjson.Set(body, path+"age-time."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"age-time."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"age-time."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"age-time."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"age-time."+"vipValue", data.AgeOutTime.ValueInt64())
	}

	if !data.MaximumMacAddressesVariable.IsNull() {
		body, _ = sjson.Set(body, path+"max-macs."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"max-macs."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"max-macs."+"vipVariableName", data.MaximumMacAddressesVariable.ValueString())
	} else if data.MaximumMacAddresses.IsNull() {
		body, _ = sjson.Set(body, path+"max-macs."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"max-macs."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"max-macs."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"max-macs."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"max-macs."+"vipValue", data.MaximumMacAddresses.ValueInt64())
	}

	if !data.VlanIdVariable.IsNull() {
		body, _ = sjson.Set(body, path+"vlan."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"vlan."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"vlan."+"vipVariableName", data.VlanIdVariable.ValueString())
	} else if data.VlanId.IsNull() {
		body, _ = sjson.Set(body, path+"vlan."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"vlan."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"vlan."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"vlan."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"vlan."+"vipValue", data.VlanId.ValueInt64())
	}
	if len(data.InterfaceToBindToBridgingDomain) > 0 {
		body, _ = sjson.Set(body, path+"interface."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"interface."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"interface."+"vipPrimaryKey", []string{"if-name"})
		body, _ = sjson.Set(body, path+"interface."+"vipValue", []interface{}{})
	} else {
		body, _ = sjson.Set(body, path+"interface."+"vipObjectType", "tree")
		body, _ = sjson.Set(body, path+"interface."+"vipType", "ignore")
		body, _ = sjson.Set(body, path+"interface."+"vipPrimaryKey", []string{"if-name"})
		body, _ = sjson.Set(body, path+"interface."+"vipValue", []interface{}{})
	}
	for _, item := range data.InterfaceToBindToBridgingDomain {
		itemBody := ""
		itemAttributes := make([]string, 0)
		itemAttributes = append(itemAttributes, "if-name")

		if !item.InterfaceNameVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "if-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "if-name."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "if-name."+"vipVariableName", item.InterfaceNameVariable.ValueString())
		} else if item.InterfaceName.IsNull() {
		} else {
			itemBody, _ = sjson.Set(itemBody, "if-name."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "if-name."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "if-name."+"vipValue", item.InterfaceName.ValueString())
		}
		itemAttributes = append(itemAttributes, "description")

		if !item.DescriptionVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "description."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "description."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "description."+"vipVariableName", item.DescriptionVariable.ValueString())
		} else if item.Description.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "description."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "description."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "description."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "description."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "description."+"vipValue", item.Description.ValueString())
		}
		itemAttributes = append(itemAttributes, "native-vlan")

		if !item.NativeVlanSupportVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipVariableName", item.NativeVlanSupportVariable.ValueString())
		} else if item.NativeVlanSupport.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "native-vlan."+"vipValue", strconv.FormatBool(item.NativeVlanSupport.ValueBool()))
		}
		itemAttributes = append(itemAttributes, "static-mac-address")
		if len(item.StaticMacAddress) > 0 {
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipObjectType", "tree")
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipPrimaryKey", []string{"macaddr"})
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipValue", []interface{}{})
		} else {
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipObjectType", "tree")
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipType", "ignore")
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipPrimaryKey", []string{"macaddr"})
			itemBody, _ = sjson.Set(itemBody, "static-mac-address."+"vipValue", []interface{}{})
		}
		for _, childItem := range item.StaticMacAddress {
			itemChildBody := ""
			itemChildAttributes := make([]string, 0)
			itemChildAttributes = append(itemChildAttributes, "macaddr")

			if !childItem.MacAddressVariable.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "macaddr."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "macaddr."+"vipType", "variableName")
				itemChildBody, _ = sjson.Set(itemChildBody, "macaddr."+"vipVariableName", childItem.MacAddressVariable.ValueString())
			} else if childItem.MacAddress.IsNull() {
			} else {
				itemChildBody, _ = sjson.Set(itemChildBody, "macaddr."+"vipObjectType", "object")
				itemChildBody, _ = sjson.Set(itemChildBody, "macaddr."+"vipType", "constant")
				itemChildBody, _ = sjson.Set(itemChildBody, "macaddr."+"vipValue", childItem.MacAddress.ValueString())
			}
			if !childItem.Optional.IsNull() {
				itemChildBody, _ = sjson.Set(itemChildBody, "vipOptional", childItem.Optional.ValueBool())
				itemChildBody, _ = sjson.Set(itemChildBody, "priority-order", itemChildAttributes)
			}
			itemBody, _ = sjson.SetRaw(itemBody, "static-mac-address."+"vipValue.-1", itemChildBody)
		}
		itemAttributes = append(itemAttributes, "shutdown")

		if !item.ShutdownVariable.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipType", "variableName")
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipVariableName", item.ShutdownVariable.ValueString())
		} else if item.Shutdown.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipType", "ignore")
		} else {
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipObjectType", "object")
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipType", "constant")
			itemBody, _ = sjson.Set(itemBody, "shutdown."+"vipValue", strconv.FormatBool(item.Shutdown.ValueBool()))
		}
		if !item.Optional.IsNull() {
			itemBody, _ = sjson.Set(itemBody, "vipOptional", item.Optional.ValueBool())
			itemBody, _ = sjson.Set(itemBody, "priority-order", itemAttributes)
		}
		body, _ = sjson.SetRaw(body, path+"interface."+"vipValue.-1", itemBody)
	}
	return body
}

func (data *Bridge) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("deviceType"); value.Exists() {
		data.DeviceTypes = helpers.GetStringSet(value.Array())
	} else {
		data.DeviceTypes = types.SetNull(types.StringType)
	}
	if value := res.Get("templateDescription"); value.Exists() && value.String() != "" {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("templateName"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("templateType"); value.Exists() {
		data.TemplateType = types.StringValue(value.String())
	} else {
		data.TemplateType = types.StringNull()
	}

	path := "templateDefinition."
	if value := res.Get(path + "name.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.BridgeName = types.StringNull()

			v := res.Get(path + "name.vipVariableName")
			data.BridgeNameVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.BridgeName = types.StringNull()
			data.BridgeNameVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "name.vipValue")
			data.BridgeName = types.StringValue(v.String())
			data.BridgeNameVariable = types.StringNull()
		}
	} else {
		data.BridgeName = types.StringNull()
		data.BridgeNameVariable = types.StringNull()
	}
	if value := res.Get(path + "age-time.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.AgeOutTime = types.Int64Null()

			v := res.Get(path + "age-time.vipVariableName")
			data.AgeOutTimeVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.AgeOutTime = types.Int64Null()
			data.AgeOutTimeVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "age-time.vipValue")
			data.AgeOutTime = types.Int64Value(v.Int())
			data.AgeOutTimeVariable = types.StringNull()
		}
	} else {
		data.AgeOutTime = types.Int64Null()
		data.AgeOutTimeVariable = types.StringNull()
	}
	if value := res.Get(path + "max-macs.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.MaximumMacAddresses = types.Int64Null()

			v := res.Get(path + "max-macs.vipVariableName")
			data.MaximumMacAddressesVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.MaximumMacAddresses = types.Int64Null()
			data.MaximumMacAddressesVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "max-macs.vipValue")
			data.MaximumMacAddresses = types.Int64Value(v.Int())
			data.MaximumMacAddressesVariable = types.StringNull()
		}
	} else {
		data.MaximumMacAddresses = types.Int64Null()
		data.MaximumMacAddressesVariable = types.StringNull()
	}
	if value := res.Get(path + "vlan.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.VlanId = types.Int64Null()

			v := res.Get(path + "vlan.vipVariableName")
			data.VlanIdVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.VlanId = types.Int64Null()
			data.VlanIdVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "vlan.vipValue")
			data.VlanId = types.Int64Value(v.Int())
			data.VlanIdVariable = types.StringNull()
		}
	} else {
		data.VlanId = types.Int64Null()
		data.VlanIdVariable = types.StringNull()
	}
	if value := res.Get(path + "interface.vipValue"); len(value.Array()) > 0 {
		data.InterfaceToBindToBridgingDomain = make([]BridgeInterfaceToBindToBridgingDomain, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := BridgeInterfaceToBindToBridgingDomain{}
			if cValue := v.Get("vipOptional"); cValue.Exists() {
				item.Optional = types.BoolValue(cValue.Bool())
			} else {
				item.Optional = types.BoolNull()
			}
			if cValue := v.Get("if-name.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.InterfaceName = types.StringNull()

					cv := v.Get("if-name.vipVariableName")
					item.InterfaceNameVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.InterfaceName = types.StringNull()
					item.InterfaceNameVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("if-name.vipValue")
					item.InterfaceName = types.StringValue(cv.String())
					item.InterfaceNameVariable = types.StringNull()
				}
			} else {
				item.InterfaceName = types.StringNull()
				item.InterfaceNameVariable = types.StringNull()
			}
			if cValue := v.Get("description.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.Description = types.StringNull()

					cv := v.Get("description.vipVariableName")
					item.DescriptionVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.Description = types.StringNull()
					item.DescriptionVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("description.vipValue")
					item.Description = types.StringValue(cv.String())
					item.DescriptionVariable = types.StringNull()
				}
			} else {
				item.Description = types.StringNull()
				item.DescriptionVariable = types.StringNull()
			}
			if cValue := v.Get("native-vlan.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.NativeVlanSupport = types.BoolNull()

					cv := v.Get("native-vlan.vipVariableName")
					item.NativeVlanSupportVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.NativeVlanSupport = types.BoolNull()
					item.NativeVlanSupportVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("native-vlan.vipValue")
					item.NativeVlanSupport = types.BoolValue(cv.Bool())
					item.NativeVlanSupportVariable = types.StringNull()
				}
			} else {
				item.NativeVlanSupport = types.BoolNull()
				item.NativeVlanSupportVariable = types.StringNull()
			}
			if cValue := v.Get("static-mac-address.vipValue"); len(cValue.Array()) > 0 {
				item.StaticMacAddress = make([]BridgeInterfaceToBindToBridgingDomainStaticMacAddress, 0)
				cValue.ForEach(func(ck, cv gjson.Result) bool {
					cItem := BridgeInterfaceToBindToBridgingDomainStaticMacAddress{}
					if ccValue := cv.Get("vipOptional"); ccValue.Exists() {
						cItem.Optional = types.BoolValue(ccValue.Bool())
					} else {
						cItem.Optional = types.BoolNull()
					}
					if ccValue := cv.Get("macaddr.vipType"); ccValue.Exists() {
						if ccValue.String() == "variableName" {
							cItem.MacAddress = types.StringNull()

							ccv := cv.Get("macaddr.vipVariableName")
							cItem.MacAddressVariable = types.StringValue(ccv.String())

						} else if ccValue.String() == "ignore" {
							cItem.MacAddress = types.StringNull()
							cItem.MacAddressVariable = types.StringNull()
						} else if ccValue.String() == "constant" {
							ccv := cv.Get("macaddr.vipValue")
							cItem.MacAddress = types.StringValue(ccv.String())
							cItem.MacAddressVariable = types.StringNull()
						}
					} else {
						cItem.MacAddress = types.StringNull()
						cItem.MacAddressVariable = types.StringNull()
					}
					item.StaticMacAddress = append(item.StaticMacAddress, cItem)
					return true
				})
			}
			if cValue := v.Get("shutdown.vipType"); cValue.Exists() {
				if cValue.String() == "variableName" {
					item.Shutdown = types.BoolNull()

					cv := v.Get("shutdown.vipVariableName")
					item.ShutdownVariable = types.StringValue(cv.String())

				} else if cValue.String() == "ignore" {
					item.Shutdown = types.BoolNull()
					item.ShutdownVariable = types.StringNull()
				} else if cValue.String() == "constant" {
					cv := v.Get("shutdown.vipValue")
					item.Shutdown = types.BoolValue(cv.Bool())
					item.ShutdownVariable = types.StringNull()
				}
			} else {
				item.Shutdown = types.BoolNull()
				item.ShutdownVariable = types.StringNull()
			}
			data.InterfaceToBindToBridgingDomain = append(data.InterfaceToBindToBridgingDomain, item)
			return true
		})
	}
}

func (data *Bridge) hasChanges(ctx context.Context, state *Bridge) bool {
	hasChanges := false
	if !data.BridgeName.Equal(state.BridgeName) {
		hasChanges = true
	}
	if !data.AgeOutTime.Equal(state.AgeOutTime) {
		hasChanges = true
	}
	if !data.MaximumMacAddresses.Equal(state.MaximumMacAddresses) {
		hasChanges = true
	}
	if !data.VlanId.Equal(state.VlanId) {
		hasChanges = true
	}
	if len(data.InterfaceToBindToBridgingDomain) != len(state.InterfaceToBindToBridgingDomain) {
		hasChanges = true
	} else {
		for i := range data.InterfaceToBindToBridgingDomain {
			if !data.InterfaceToBindToBridgingDomain[i].InterfaceName.Equal(state.InterfaceToBindToBridgingDomain[i].InterfaceName) {
				hasChanges = true
			}
			if !data.InterfaceToBindToBridgingDomain[i].Description.Equal(state.InterfaceToBindToBridgingDomain[i].Description) {
				hasChanges = true
			}
			if !data.InterfaceToBindToBridgingDomain[i].NativeVlanSupport.Equal(state.InterfaceToBindToBridgingDomain[i].NativeVlanSupport) {
				hasChanges = true
			}
			if len(data.InterfaceToBindToBridgingDomain[i].StaticMacAddress) != len(state.InterfaceToBindToBridgingDomain[i].StaticMacAddress) {
				hasChanges = true
			} else {
				for ii := range data.InterfaceToBindToBridgingDomain[i].StaticMacAddress {
					if !data.InterfaceToBindToBridgingDomain[i].StaticMacAddress[ii].MacAddress.Equal(state.InterfaceToBindToBridgingDomain[i].StaticMacAddress[ii].MacAddress) {
						hasChanges = true
					}
				}
			}
			if !data.InterfaceToBindToBridgingDomain[i].Shutdown.Equal(state.InterfaceToBindToBridgingDomain[i].Shutdown) {
				hasChanges = true
			}
		}
	}
	return hasChanges
}
