// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/CiscoDevNet/terraform-provider-sdwan/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type Archive struct {
	Id                                 types.String `tfsdk:"id"`
	Version                            types.Int64  `tfsdk:"version"`
	TemplateType                       types.String `tfsdk:"template_type"`
	Name                               types.String `tfsdk:"name"`
	Description                        types.String `tfsdk:"description"`
	DeviceTypes                        types.Set    `tfsdk:"device_types"`
	PathToArchiveFileDirectory         types.String `tfsdk:"path_to_archive_file_directory"`
	PathToArchiveFileDirectoryVariable types.String `tfsdk:"path_to_archive_file_directory_variable"`
	ArchivalInterval                   types.Int64  `tfsdk:"archival_interval"`
	ArchivalIntervalVariable           types.String `tfsdk:"archival_interval_variable"`
	SshKeyFile                         types.String `tfsdk:"ssh_key_file"`
	SshKeyFileVariable                 types.String `tfsdk:"ssh_key_file_variable"`
	VpnId                              types.Int64  `tfsdk:"vpn_id"`
	VpnIdVariable                      types.String `tfsdk:"vpn_id_variable"`
}

func (data Archive) getModel() string {
	return "archive"
}

func (data Archive) toBody(ctx context.Context) string {
	body := ""

	var device_types []string
	data.DeviceTypes.ElementsAs(ctx, &device_types, false)
	body, _ = sjson.Set(body, "deviceType", device_types)
	body, _ = sjson.Set(body, "factoryDefault", false)
	body, _ = sjson.Set(body, "templateDescription", data.Description.ValueString())
	body, _ = sjson.Set(body, "templateMinVersion", "15.0.0")
	body, _ = sjson.Set(body, "templateName", data.Name.ValueString())
	body, _ = sjson.Set(body, "templateType", "archive")
	body, _ = sjson.Set(body, "templateDefinition", map[string]interface{}{})

	path := "templateDefinition."

	if !data.PathToArchiveFileDirectoryVariable.IsNull() {
		body, _ = sjson.Set(body, path+"path."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"path."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"path."+"vipVariableName", data.PathToArchiveFileDirectoryVariable.ValueString())
	} else if data.PathToArchiveFileDirectory.IsNull() {
	} else {
		body, _ = sjson.Set(body, path+"path."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"path."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"path."+"vipValue", data.PathToArchiveFileDirectory.ValueString())
	}

	if !data.ArchivalIntervalVariable.IsNull() {
		body, _ = sjson.Set(body, path+"interval."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"interval."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"interval."+"vipVariableName", data.ArchivalIntervalVariable.ValueString())
	} else if data.ArchivalInterval.IsNull() {
		body, _ = sjson.Set(body, path+"interval."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"interval."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"interval."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"interval."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"interval."+"vipValue", data.ArchivalInterval.ValueInt64())
	}

	if !data.SshKeyFileVariable.IsNull() {
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipVariableName", data.SshKeyFileVariable.ValueString())
	} else if data.SshKeyFile.IsNull() {
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"ssh-id-file."+"vipValue", data.SshKeyFile.ValueString())
	}

	if !data.VpnIdVariable.IsNull() {
		body, _ = sjson.Set(body, path+"vpn."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"vpn."+"vipType", "variableName")
		body, _ = sjson.Set(body, path+"vpn."+"vipVariableName", data.VpnIdVariable.ValueString())
	} else if data.VpnId.IsNull() {
		body, _ = sjson.Set(body, path+"vpn."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"vpn."+"vipType", "ignore")
	} else {
		body, _ = sjson.Set(body, path+"vpn."+"vipObjectType", "object")
		body, _ = sjson.Set(body, path+"vpn."+"vipType", "constant")
		body, _ = sjson.Set(body, path+"vpn."+"vipValue", data.VpnId.ValueInt64())
	}
	return body
}

func (data *Archive) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("deviceType"); value.Exists() {
		data.DeviceTypes = helpers.GetStringSet(value.Array())
	} else {
		data.DeviceTypes = types.SetNull(types.StringType)
	}
	if value := res.Get("templateDescription"); value.Exists() && value.String() != "" {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("templateName"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("templateType"); value.Exists() {
		data.TemplateType = types.StringValue(value.String())
	} else {
		data.TemplateType = types.StringNull()
	}

	path := "templateDefinition."
	if value := res.Get(path + "path.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.PathToArchiveFileDirectory = types.StringNull()

			v := res.Get(path + "path.vipVariableName")
			data.PathToArchiveFileDirectoryVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.PathToArchiveFileDirectory = types.StringNull()
			data.PathToArchiveFileDirectoryVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "path.vipValue")
			data.PathToArchiveFileDirectory = types.StringValue(v.String())
			data.PathToArchiveFileDirectoryVariable = types.StringNull()
		}
	} else {
		data.PathToArchiveFileDirectory = types.StringNull()
		data.PathToArchiveFileDirectoryVariable = types.StringNull()
	}
	if value := res.Get(path + "interval.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.ArchivalInterval = types.Int64Null()

			v := res.Get(path + "interval.vipVariableName")
			data.ArchivalIntervalVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.ArchivalInterval = types.Int64Null()
			data.ArchivalIntervalVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "interval.vipValue")
			data.ArchivalInterval = types.Int64Value(v.Int())
			data.ArchivalIntervalVariable = types.StringNull()
		}
	} else {
		data.ArchivalInterval = types.Int64Null()
		data.ArchivalIntervalVariable = types.StringNull()
	}
	if value := res.Get(path + "ssh-id-file.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.SshKeyFile = types.StringNull()

			v := res.Get(path + "ssh-id-file.vipVariableName")
			data.SshKeyFileVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.SshKeyFile = types.StringNull()
			data.SshKeyFileVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "ssh-id-file.vipValue")
			data.SshKeyFile = types.StringValue(v.String())
			data.SshKeyFileVariable = types.StringNull()
		}
	} else {
		data.SshKeyFile = types.StringNull()
		data.SshKeyFileVariable = types.StringNull()
	}
	if value := res.Get(path + "vpn.vipType"); value.Exists() {
		if value.String() == "variableName" {
			data.VpnId = types.Int64Null()

			v := res.Get(path + "vpn.vipVariableName")
			data.VpnIdVariable = types.StringValue(v.String())

		} else if value.String() == "ignore" {
			data.VpnId = types.Int64Null()
			data.VpnIdVariable = types.StringNull()
		} else if value.String() == "constant" {
			v := res.Get(path + "vpn.vipValue")
			data.VpnId = types.Int64Value(v.Int())
			data.VpnIdVariable = types.StringNull()
		}
	} else {
		data.VpnId = types.Int64Null()
		data.VpnIdVariable = types.StringNull()
	}
}

func (data *Archive) hasChanges(ctx context.Context, state *Archive) bool {
	hasChanges := false
	if !data.PathToArchiveFileDirectory.Equal(state.PathToArchiveFileDirectory) {
		hasChanges = true
	}
	if !data.ArchivalInterval.Equal(state.ArchivalInterval) {
		hasChanges = true
	}
	if !data.SshKeyFile.Equal(state.SshKeyFile) {
		hasChanges = true
	}
	if !data.VpnId.Equal(state.VpnId) {
		hasChanges = true
	}
	return hasChanges
}
