// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanSystemMRFProfileParcel(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanSystemMRFProfileParcelConfig_minimum(),
				Check:  resource.ComposeTestCheckFunc(),
			},
			{
				Config: testAccSdwanSystemMRFProfileParcelConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_system_mrf_profile_parcel.test", "region_id", "1"),
					resource.TestCheckResourceAttr("sdwan_system_mrf_profile_parcel.test", "secondary_region", "2"),
					resource.TestCheckResourceAttr("sdwan_system_mrf_profile_parcel.test", "role", "edge-router"),
					resource.TestCheckResourceAttr("sdwan_system_mrf_profile_parcel.test", "enable_mrf_migration", "enabled"),
					resource.TestCheckResourceAttr("sdwan_system_mrf_profile_parcel.test", "migration_bgp_community", "100"),
				),
			},
		},
	})
}

func testAccSdwanSystemMRFProfileParcelConfig_minimum() string {
	return `
	resource "sdwan_system_feature_profile" "test" {
  name = "TF_TEST"
  description = "Terraform test"
}

	resource "sdwan_system_mrf_profile_parcel" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		feature_profile_id = sdwan_system_feature_profile.test.id
	}
	`
}

func testAccSdwanSystemMRFProfileParcelConfig_all() string {
	return `
	resource "sdwan_system_feature_profile" "test" {
  name = "TF_TEST"
  description = "Terraform test"
}

	resource "sdwan_system_mrf_profile_parcel" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		feature_profile_id = sdwan_system_feature_profile.test.id
		region_id = 1
		secondary_region = 2
		role = "edge-router"
		enable_mrf_migration = "enabled"
		migration_bgp_community = 100
	}
	`
}
