// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanNtpFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanNtpFeatureTemplateConfig_minimum(),
				Check:  resource.ComposeTestCheckFunc(),
			},
			{
				Config: testAccSdwanNtpFeatureTemplateConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "ntp_servers.0.hostname_ip_address", "example"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "ntp_servers.0.authentication_key", "12345"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "ntp_servers.0.vpn_id", "1"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "ntp_servers.0.version", "3"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "ntp_servers.0.source_interface", "18"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "ntp_servers.0.prefer", "false"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "authentication.0.md5_authentication_key_id", "23456"),
					resource.TestCheckResourceAttr("sdwan_ntp_feature_template.test", "authentication.0.authentication_value", "MyPassword"),
				),
			},
		},
	})
}

func testAccSdwanNtpFeatureTemplateConfig_minimum() string {
	return `
	resource "sdwan_ntp_feature_template" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
	}
	`
}

func testAccSdwanNtpFeatureTemplateConfig_all() string {
	return `
	resource "sdwan_ntp_feature_template" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		ntp_servers = [{
			hostname_ip_address = "example"
			authentication_key = 12345
			vpn_id = 1
			version = 3
			source_interface = "18"
			prefer = false
		}]
		authentication = [{
			md5_authentication_key_id = 23456
			authentication_value = "MyPassword"
		}]
		trusted_keys = [1234]
	}
	`
}
