// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanBridgeFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanBridgeFeatureTemplateConfig_minimum(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "bridge_name", "example"),
				),
			},
			{
				Config: testAccSdwanBridgeFeatureTemplateConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "bridge_name", "example"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "age_out_time", "300"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "maximum_mac_addresses", "1234"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "vlan_id", "1"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "interface_to_bind_to_bridging_domain.0.interface_name", "interface_example"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "interface_to_bind_to_bridging_domain.0.description", "My Description"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "interface_to_bind_to_bridging_domain.0.native_vlan_support", "false"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "interface_to_bind_to_bridging_domain.0.static_mac_address.0.mac_address", "0000.00000.0000"),
					resource.TestCheckResourceAttr("sdwan_bridge_feature_template.test", "interface_to_bind_to_bridging_domain.0.shutdown", "true"),
				),
			},
		},
	})
}

func testAccSdwanBridgeFeatureTemplateConfig_minimum() string {
	return `
	resource "sdwan_bridge_feature_template" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		bridge_name = "example"
	}
	`
}

func testAccSdwanBridgeFeatureTemplateConfig_all() string {
	return `
	resource "sdwan_bridge_feature_template" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		bridge_name = "example"
		age_out_time = 300
		maximum_mac_addresses = 1234
		vlan_id = 1
		interface_to_bind_to_bridging_domain = [{
			interface_name = "interface_example"
			description = "My Description"
			native_vlan_support = false
			static_mac_address = [{
				mac_address = "0000.00000.0000"
			}]
			shutdown = true
		}]
	}
	`
}
