// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanOspfFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanOspfFeatureTemplateConfig_minimum(),
				Check:  resource.ComposeTestCheckFunc(),
			},
			{
				Config: testAccSdwanOspfFeatureTemplateConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "router_id", "1.2.3.4"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "reference_bandwidth", "429496"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "rfc_1583_compatible", "true"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "originate_default_route", "false"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "always", "false"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "default_metric", "16777"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "metric_type", "type2"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "distance_for_external_routes", "110"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "distance_for_inter_area_routes", "110"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "distance_for_intra_area_routes", "110"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "spf_calculation_delay", "200"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "initial_hold_time", "1000"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "max_hold_time", "1000"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "redistribute_routes.0.protocol", "static"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "redistribute_routes.0.route_policy", "example"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "router_lsa.0.type", "administrative"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "router_lsa.0.advertizement_time", "1234"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "route_policies.0.direction", "in"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "route_policies.0.policy_name", "example"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.area_number", "42949672"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.stub_no_summary", "false"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.translate", "candidate"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.nssa_no_summary", "false"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.interface_name", "interface_example"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.hello_interval", "10"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.dead_interval", "40"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.retransmit_interval", "5"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.interface_cost", "1234"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.designated_router_priority", "1"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.ospf_network_type", "broadcast"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.passive_interface", "false"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.authentication_type", "simple"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.authentication_key", "example"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.message_digest_key_id", "1"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.ospf_interface.0.message_digest_key", "MyMD5Key"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.summarize_routes.0.address", "1.2.3.4/24"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.summarize_routes.0.cost", "167215"),
					resource.TestCheckResourceAttr("sdwan_ospf_feature_template.test", "ospf_area.0.summarize_routes.0.no_advertise", "false"),
				),
			},
		},
	})
}

func testAccSdwanOspfFeatureTemplateConfig_minimum() string {
	return `
	resource "sdwan_ospf_feature_template" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
	}
	`
}

func testAccSdwanOspfFeatureTemplateConfig_all() string {
	return `
	resource "sdwan_ospf_feature_template" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		router_id = "1.2.3.4"
		reference_bandwidth = 429496
		rfc_1583_compatible = true
		originate_default_route = false
		always = false
		default_metric = 16777
		metric_type = "type2"
		distance_for_external_routes = 110
		distance_for_inter_area_routes = 110
		distance_for_intra_area_routes = 110
		spf_calculation_delay = 200
		initial_hold_time = 1000
		max_hold_time = 1000
		redistribute_routes = [{
			protocol = "static"
			route_policy = "example"
		}]
		router_lsa = [{
			type = "administrative"
			advertizement_time = 1234
		}]
		route_policies = [{
			direction = "in"
			policy_name = "example"
		}]
		ospf_area = [{
			area_number = 42949672
			stub_no_summary = false
			translate = "candidate"
			nssa_no_summary = false
			ospf_interface = [{
				interface_name = "interface_example"
				hello_interval = 10
				dead_interval = 40
				retransmit_interval = 5
				interface_cost = 1234
				designated_router_priority = 1
				ospf_network_type = "broadcast"
				passive_interface = false
				authentication_type = "simple"
				authentication_key = "example"
				message_digest_key_id = 1
				message_digest_key = "MyMD5Key"
			}]
			summarize_routes = [{
				address = "1.2.3.4/24"
				cost = 167215
				no_advertise = false
			}]
		}]
	}
	`
}
