// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccSdwanPimFeatureTemplate(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccSdwanPimFeatureTemplateConfig_minimum(),
				Check:  resource.ComposeTestCheckFunc(),
			},
			{
				Config: testAccSdwanPimFeatureTemplateConfig_all(),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "shutdown", "false"),
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "auto_rp", "false"),
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "spt_threshold", "64"),
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "replicator", "random"),
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "interface.0.interface_name", "example"),
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "interface.0.hello_interval", "1200"),
					resource.TestCheckResourceAttr("sdwan_pim_feature_template.test", "interface.0.join_prune_interval", "123"),
				),
			},
		},
	})
}

func testAccSdwanPimFeatureTemplateConfig_minimum() string {
	return `
	resource "sdwan_pim_feature_template" "test" {
		name = "TF_TEST_MIN"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
	}
	`
}

func testAccSdwanPimFeatureTemplateConfig_all() string {
	return `
	resource "sdwan_pim_feature_template" "test" {
		name = "TF_TEST_ALL"
		description = "Terraform integration test"
		device_types = ["vedge-C8000V"]
		shutdown = false
		auto_rp = false
		spt_threshold = 64
		replicator = "random"
		interface = [{
			interface_name = "example"
			hello_interval = 1200
			join_prune_interval = 123
		}]
	}
	`
}
